freeslot(
//Sonic
"sfx_sowoln", "sfx_socoln", "sfx_sodiln", "sfx_someln", "sfx_sogrln", "sfx_sowaln", "sfx_soglln",
"sfx_sowobr", "sfx_socobr", "sfx_sodibr", "sfx_somebr", "sfx_sogrbr", "sfx_sowabr", "sfx_soglbr",
"sfx_soco1", "sfx_soco2", "sfx_soco3", "sfx_soco4", "sfx_soco5",
"sfx_sodi1", "sfx_sodi2", "sfx_sodi3", "sfx_sodi4", "sfx_sodi5",
"sfx_sogl1", "sfx_sogl2", "sfx_sogl3",
"sfx_sogr1", "sfx_sogr2", "sfx_sogr3", "sfx_sogr4", "sfx_sogr5",
"sfx_some1", "sfx_some2", "sfx_some3", "sfx_some4", "sfx_some5",
"sfx_sowa1", "sfx_sowa2", "sfx_sowa3", "sfx_sowa4", "sfx_sowa5",
"sfx_sowo1", "sfx_sowo2", "sfx_sowo3", "sfx_sowo4", "sfx_sowo5",
//S4 League
"sfx_s4woln", "sfx_s4coln", "sfx_s4diln", "sfx_s4meln", "sfx_s4grln", "sfx_s4waln", "sfx_s4glln",
"sfx_s4co1", "sfx_s4co2", "sfx_s4co3", "sfx_s4co4",
"sfx_s4di1", "sfx_s4di2", "sfx_s4di3", "sfx_s4di4",
"sfx_s4gr1", "sfx_s4gr2", "sfx_s4gr3", "sfx_s4gr4",
"sfx_s4me1", "sfx_s4me2", "sfx_s4me3", "sfx_s4me4",
"sfx_s4wa1", "sfx_s4wa2", "sfx_s4wa3", "sfx_s4wa4",
"sfx_s4wo1", "sfx_s4wo2", "sfx_s4wo3", "sfx_s4wo4",
//HL
"sfx_hlco1", "sfx_hlco2", "sfx_hlco3", "sfx_hlco4",
"sfx_hldi1", "sfx_hldi2", "sfx_hldi3", "sfx_hldi4",
"sfx_hlgl1", "sfx_hlgl2", "sfx_hlgl3", "sfx_hlgl4", "sfx_hlgl5",
"sfx_hlme1", "sfx_hlme2", "sfx_hlme3", "sfx_hlme4",
"sfx_hlwa1", "sfx_hlwa2", "sfx_hlwa3", "sfx_hlwa4",
//HL2
"sfx_h2co1", "sfx_h2co2", "sfx_h2co3", "sfx_h2co4",
"sfx_h2di1", "sfx_h2di2", "sfx_h2di3", "sfx_h2di4",
"sfx_h2gl1", "sfx_h2gl2", "sfx_h2gl3", "sfx_h2gl4",
"sfx_h2gr1", "sfx_h2gr2", "sfx_h2gr3", "sfx_h2gr4",
"sfx_h2me1", "sfx_h2me2", "sfx_h2me3", "sfx_h2me4",
"sfx_h2wa1", "sfx_h2wa2", "sfx_h2wa3", "sfx_h2wa4",
"sfx_h2wo1", "sfx_h2wo2", "sfx_h2wo3", "sfx_h2wo4",
//H2 Extra FUN
"sfx_h2fu1", "sfx_h2fu2", "sfx_h2fu3", "sfx_h2fu4",
//TLOZ:OT
"sfx_zeco1", "sfx_zeco2", "sfx_zeco3", "sfx_zeco4", "sfx_zeco5", "sfx_zeco6",
"sfx_zedi1", "sfx_zedi2", "sfx_zedi3", "sfx_zedi4", "sfx_zedi5", "sfx_zedi6",
"sfx_zecl1", "sfx_zecl2", "sfx_zecl3", "sfx_zecl4", "sfx_zecl5",
"sfx_zesa1", "sfx_zesa2", "sfx_zesa3", "sfx_zesa4", "sfx_zesa5",
"sfx_zegl1", "sfx_zegl2",
"sfx_zegr1", "sfx_zegr2", "sfx_zegr3", "sfx_zegr4", "sfx_zegr5", "sfx_zegr6", "sfx_zegr7",
"sfx_zewa1", "sfx_zewa2", "sfx_zewa3", "sfx_zewa4",
"sfx_zela1", "sfx_zela2", "sfx_zela3",
"sfx_zewo1", "sfx_zewo2", "sfx_zewo3", "sfx_zewo4", "sfx_zewo5",
//Minecraft
"sfx_migr1", "sfx_migr2", "sfx_migr3", "sfx_migr4", "sfx_migr5", "sfx_migr6",
"sfx_mico1", "sfx_mico2", "sfx_mico3", "sfx_mico4", "sfx_mico5", "sfx_mico6",
"sfx_midi1", "sfx_midi2", "sfx_midi3", "sfx_midi4",
"sfx_misn1", "sfx_misn2", "sfx_misn3", "sfx_misn4",
"sfx_micl1", "sfx_micl2", "sfx_micl3", "sfx_micl4",
"sfx_misa1", "sfx_misa2", "sfx_misa3", "sfx_misa4", "sfx_misa5",
"sfx_miwh1", "sfx_miwh2", "sfx_miwh3", "sfx_miwh4", "sfx_miwh5", "sfx_miwh6",
"sfx_miwl1", "sfx_miwl2", "sfx_miwl3", "sfx_miwl4", "sfx_miwl5", "sfx_miwl6",
"sfx_miwa1", "sfx_miwa2", "sfx_miwa3", "sfx_miwa4",
"sfx_mila1", "sfx_mila2", "sfx_mila3", "sfx_mila4"
)

if not SoundListInfo
	rawset(_G, "SoundListInfo", {})
end

if not PlayerAnimInfo
	rawset(_G, "PlayerAnimInfo", {})
end

local soundinfolist = {
	["sonic"] = {
		["grass"] = {
		  ["steps"] = {sfx_sogr1, sfx_sogr2, sfx_sogr3, sfx_sogr4, sfx_sogr5},
		  ["skid"] = {sfx_sogrbr},
		  ["land"] = {sfx_sogrln},
		},
		["metal_heavy"] = {
		  ["steps"] = {sfx_some1, sfx_some2, sfx_some3, sfx_some4, sfx_some5},
		  ["skid"] = {sfx_somebr},
		  ["land"] = {sfx_someln},
		},
		["metal_light"] = {
		  ["steps"] = {sfx_some1, sfx_some2, sfx_some3, sfx_some4, sfx_some5},
		  ["skid"] = {sfx_somebr},
		  ["land"] = {sfx_someln},
		},
		["dirt"] = {
		  ["steps"] = {sfx_sodi1, sfx_sodi2, sfx_sodi3, sfx_sodi4, sfx_sodi5},
		  ["skid"] = {sfx_sodibr},
		  ["land"] = {sfx_sodiln},
		},
		["snow"] = {
		  ["steps"] = {sfx_sodi1, sfx_sodi2, sfx_sodi3, sfx_sodi4, sfx_sodi5},
		  ["skid"] = {sfx_sodibr},
		  ["land"] = {sfx_sodiln},
		},
		["cloth"] = {
		  ["steps"] = {sfx_sodi1, sfx_sodi2, sfx_sodi3, sfx_sodi4, sfx_sodi5},
		  ["skid"] = {sfx_sodibr},
		  ["land"] = {sfx_sodiln},
		},
		["sand"] = {
		  ["steps"] = {sfx_sodi1, sfx_sodi2, sfx_sodi3, sfx_sodi4, sfx_sodi5},
		  ["skid"] = {sfx_sodibr},
		  ["land"] = {sfx_sodiln},
		},
		["wood_heavy"] = {
		  ["steps"] = {sfx_sowo1, sfx_sowo2, sfx_sowo3, sfx_sowo4, sfx_sowo5},
		  ["skid"] = {sfx_sowobr},
		  ["land"] = {sfx_sowoln},
		},
		["wood_light"] = {
		  ["steps"] = {sfx_sowo1, sfx_sowo2, sfx_sowo3, sfx_sowo4, sfx_sowo5},
		  ["skid"] = {sfx_sowobr},
		  ["land"] = {sfx_sowoln},
		},
		["concrete"] = {
		  ["steps"] = {sfx_soco1, sfx_soco2, sfx_soco3, sfx_soco4, sfx_soco5},
		  ["skid"] = {sfx_socobr},
		  ["land"] = {sfx_socoln},
		},
		["water"] = {
		  ["steps"] = {sfx_sowa1, sfx_sowa2, sfx_sowa3, sfx_sowa4, sfx_sowa5},
		  ["skid"] = {sfx_sowabr},
		  ["land"] = {sfx_sowaln},
		},
		["lava"] = {
		  ["steps"] = {sfx_sowa1, sfx_sowa2, sfx_sowa3, sfx_sowa4, sfx_sowa5},
		  ["skid"] = {sfx_sowabr},
		  ["land"] = {sfx_sowaln},
		},
		["glass"] = {
		  ["steps"] = {sfx_sogl1, sfx_sogl2, sfx_sogl3},
		  ["skid"] = {sfx_soglbr},
		  ["land"] = {sfx_soglln},
		}
	},
	["s4"] = {
		["grass"] = {
		  ["steps"] = {sfx_s4gr1, sfx_s4gr2, sfx_s4gr3, sfx_s4gr4},
		  ["land"] = {sfx_s4grln}
		},
		["metal_heavy"] = {
		  ["steps"] = {sfx_s4me1, sfx_s4me2, sfx_s4me3, sfx_s4me4},
		  ["land"] = {sfx_s4meln}
		},
		["metal_light"] = {
		  ["steps"] = {sfx_s4me1, sfx_s4me2, sfx_s4me3, sfx_s4me4},
		  ["land"] = {sfx_s4meln}
		},
		["dirt"] = {
		  ["steps"] = {sfx_s4di1, sfx_s4di2, sfx_s4di3, sfx_s4di4},
		  ["land"] = {sfx_s4diln}
		},
		["snow"] = {
		  ["steps"] = {sfx_s4di1, sfx_s4di2, sfx_s4di3, sfx_s4di4},
		  ["land"] = {sfx_s4diln}
		},
		["cloth"] = {
		  ["steps"] = {sfx_s4di1, sfx_s4di2, sfx_s4di3, sfx_s4di4},
		  ["land"] = {sfx_s4diln}
		},
		["sand"] = {
		  ["steps"] = {sfx_s4di1, sfx_s4di2, sfx_s4di3, sfx_s4di4},
		  ["land"] = {sfx_s4diln}
		},		
		["wood_heavy"] = {
		  ["steps"] = {sfx_s4wo1, sfx_s4wo2, sfx_s4wo3, sfx_s4wo4},
		  ["land"] = {sfx_s4woln}
		},
		["wood_light"] = {
		  ["steps"] = {sfx_s4wo1, sfx_s4wo2, sfx_s4wo3, sfx_s4wo4},
		  ["land"] = {sfx_s4woln}
		},
		["concrete"] = {
		  ["steps"] = {sfx_s4co1, sfx_s4co2, sfx_s4co3, sfx_s4co4},
		  ["land"] = {sfx_s4coln}
		},
		["water"] = {
		  ["steps"] = {sfx_s4wa1, sfx_s4wa2, sfx_s4wa3, sfx_s4wa4},
		  ["land"] = {sfx_s4waln}
		},
		["lava"] = {
		  ["steps"] = {sfx_s4wa1, sfx_s4wa2, sfx_s4wa3, sfx_s4wa4},
		  ["land"] = {sfx_s4waln}
		},
		["glass"] = {
		  ["steps"] = {sfx_s4co1, sfx_s4co2, sfx_s4co3, sfx_s4co4},
		  ["land"] = {sfx_s4coln}
		}
	},
	["hl"] = {
		["grass"] = {
		  ["steps"] = {sfx_hldi1, sfx_hldi2, sfx_hldi3, sfx_hldi4},
		  ["land"] = {sfx_hldi1, sfx_hldi2, sfx_hldi3, sfx_hldi4}
		},
		["metal_heavy"] = {
		  ["steps"] = {sfx_hlme1, sfx_hlme2, sfx_hlme3, sfx_hlme4},
		  ["land"] = {sfx_hlme1, sfx_hlme2, sfx_hlme3, sfx_hlme4}
		},
		["metal_light"] = {
		  ["steps"] = {sfx_hlme1, sfx_hlme2, sfx_hlme3, sfx_hlme4},
		  ["land"] = {sfx_hlme1, sfx_hlme2, sfx_hlme3, sfx_hlme4}
		},
		["dirt"] = {
		  ["steps"] = {sfx_hldi1, sfx_hldi2, sfx_hldi3, sfx_hldi4},
		  ["land"] = {sfx_hldi1, sfx_hldi2, sfx_hldi3, sfx_hldi4}
		},
		["snow"] = {
		  ["steps"] = {sfx_hldi1, sfx_hldi2, sfx_hldi3, sfx_hldi4},
		  ["land"] = {sfx_hldi1, sfx_hldi2, sfx_hldi3, sfx_hldi4}
		},
		["cloth"] = {
		  ["steps"] = {sfx_hldi1, sfx_hldi2, sfx_hldi3, sfx_hldi4},
		  ["land"] = {sfx_hldi1, sfx_hldi2, sfx_hldi3, sfx_hldi4}
		},
		["sand"] = {
		  ["steps"] = {sfx_hldi1, sfx_hldi2, sfx_hldi3, sfx_hldi4},
		  ["land"] = {sfx_hldi1, sfx_hldi2, sfx_hldi3, sfx_hldi4}
		},			
		["wood_heavy"] = {
		  ["steps"] = {sfx_hlco1, sfx_hlco2, sfx_hlco3, sfx_hlco4},
		  ["land"] = {sfx_hlco1, sfx_hlco2, sfx_hlco3, sfx_hlco4}
		},
		["wood_light"] = {
		  ["steps"] = {sfx_hlco1, sfx_hlco2, sfx_hlco3, sfx_hlco4},
		  ["land"] = {sfx_hlco1, sfx_hlco2, sfx_hlco3, sfx_hlco4}
		},
		["concrete"] = {
		  ["steps"] = {sfx_hlco1, sfx_hlco2, sfx_hlco3, sfx_hlco4},
		  ["land"] = {sfx_hlco1, sfx_hlco2, sfx_hlco3, sfx_hlco4}
		},
		["water"] = {
		  ["steps"] = {sfx_hlwa1, sfx_hlwa2, sfx_hlwa3, sfx_hlwa4},
		  ["land"] = {sfx_hlwa1, sfx_hlwa2, sfx_hlwa3, sfx_hlwa4}
		},
		["lava"] = {
		  ["steps"] = {sfx_hlwa1, sfx_hlwa2, sfx_hlwa3, sfx_hlwa4},
		  ["land"] = {sfx_hlwa1, sfx_hlwa2, sfx_hlwa3, sfx_hlwa4}
		},		
		["glass"] = {
		  ["steps"] = {sfx_hlgl1, sfx_hlgl2, sfx_hlgl3, sfx_hlgl4, sfx_hlgl5},
		  ["land"] = {sfx_hlgl1, sfx_hlgl2, sfx_hlgl3, sfx_hlgl4, sfx_hlgl5}
		}
	},
	["h2"] = {
		["grass"] = {
		  ["steps"] = {sfx_h2gr1, sfx_h2gr2, sfx_h2gr3, sfx_h2gr4},
		  ["land"] = {sfx_h2gr1, sfx_h2gr2, sfx_h2gr3, sfx_h2gr4}
		},
		["metal_heavy"] = {
		  ["steps"] = {sfx_h2me1, sfx_h2me2, sfx_h2me3, sfx_h2me4},
		  ["land"] = {sfx_h2me1, sfx_h2me2, sfx_h2me3, sfx_h2me4}
		},
		["metal_light"] = {
		  ["steps"] = {sfx_h2me1, sfx_h2me2, sfx_h2me3, sfx_h2me4},
		  ["land"] = {sfx_h2me1, sfx_h2me2, sfx_h2me3, sfx_h2me4}
		},
		["dirt"] = {
		  ["steps"] = {sfx_h2di1, sfx_h2di2, sfx_h2di3, sfx_h2di4},
		  ["land"] = {sfx_h2di1, sfx_h2di2, sfx_h2di3, sfx_h2di4}
		},
		["snow"] = {
		  ["steps"] = {sfx_h2di1, sfx_h2di2, sfx_h2di3, sfx_h2di4},
		  ["land"] = {sfx_h2di1, sfx_h2di2, sfx_h2di3, sfx_h2di4}
		},
		["cloth"] = {
		  ["steps"] = {sfx_h2di1, sfx_h2di2, sfx_h2di3, sfx_h2di4},
		  ["land"] = {sfx_h2di1, sfx_h2di2, sfx_h2di3, sfx_h2di4}
		},
		["sand"] = {
		  ["steps"] = {sfx_h2di1, sfx_h2di2, sfx_h2di3, sfx_h2di4},
		  ["land"] = {sfx_h2di1, sfx_h2di2, sfx_h2di3, sfx_h2di4}
		},		
		["wood_heavy"] = {
		  ["steps"] = {sfx_h2wo1, sfx_h2wo2, sfx_h2wo3, sfx_h2wo4},
		  ["land"] = {sfx_h2wo1, sfx_h2wo2, sfx_h2wo3, sfx_h2wo4}
		},
		["wood_light"] = {
		  ["steps"] = {sfx_h2wo1, sfx_h2wo2, sfx_h2wo3, sfx_h2wo4},
		  ["land"] = {sfx_h2wo1, sfx_h2wo2, sfx_h2wo3, sfx_h2wo4}
		},		
		["concrete"] = {
		  ["steps"] = {sfx_h2co1, sfx_h2co2, sfx_h2co3, sfx_h2co4},
		  ["land"] = {sfx_h2co1, sfx_h2co2, sfx_h2co3, sfx_h2co4}
		},
		["water"] = {
		  ["steps"] = {sfx_h2wa1, sfx_h2wa2, sfx_h2wa3, sfx_h2wa4},
		  ["land"] = {sfx_h2wa1, sfx_h2wa2, sfx_h2wa3, sfx_h2wa4}
		},
		["lava"] = {
		  ["steps"] = {sfx_h2wa1, sfx_h2wa2, sfx_h2wa3, sfx_h2wa4},
		  ["land"] = {sfx_h2wa1, sfx_h2wa2, sfx_h2wa3, sfx_h2wa4}
		},		
		["glass"] = {
		  ["steps"] = {sfx_h2gl1, sfx_h2gl2, sfx_h2gl3, sfx_h2gl4},
		  ["land"] = {sfx_h2gl1, sfx_h2gl2, sfx_h2gl3, sfx_h2gl4}
		}	
	},
	["h2fun"] = {
		["grass"] = {
		  ["steps"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4},
		  ["land"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4}
		},
		["metal_heavy"] = {
		  ["steps"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4},
		  ["land"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4}
		},
		["metal_light"] = {
		  ["steps"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4},
		  ["land"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4}
		},
		["dirt"] = {
		  ["steps"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4},
		  ["land"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4}
		},
		["snow"] = {
		  ["steps"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4},
		  ["land"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4}
		},
		["sand"] = {
		  ["steps"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4},
		  ["land"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4}
		},		
		["cloth"] = {
		  ["steps"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4},
		  ["land"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4}
		},		
		["wood_heavy"] = {
		  ["steps"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4},
		  ["land"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4}
		},
		["wood_light"] = {
		  ["steps"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4},
		  ["land"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4}
		},		
		["concrete"] = {
		  ["steps"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4},
		  ["land"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4}
		},
		["water"] = {
		  ["steps"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4},
		  ["land"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4}
		},
		["lava"] = {
		  ["steps"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4},
		  ["land"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4}
		},		
		["glass"] = {
		  ["steps"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4},
		  ["land"] = {sfx_h2fu1, sfx_h2fu2, sfx_h2fu3, sfx_h2fu4}
		}	
	},
	["zelda"] = {
		["grass"] = {
		  ["steps"] = {sfx_zegr1, sfx_zegr2, sfx_zegr3, sfx_zegr4, sfx_zegr5, sfx_zegr6, sfx_zegr7},
		  ["land"] = {sfx_zegr1, sfx_zegr2, sfx_zegr3, sfx_zegr4, sfx_zegr5, sfx_zegr6, sfx_zegr7}
		},
		["metal_heavy"] = {
		  ["steps"] = {sfx_zeco1, sfx_zeco2, sfx_zeco3, sfx_zeco4, sfx_zeco5, sfx_zeco6},
		  ["land"] = {sfx_zeco1, sfx_zeco2, sfx_zeco3, sfx_zeco4, sfx_zeco5, sfx_zeco6}
		},
		["metal_light"] = {
		  ["steps"] = {sfx_zeco1, sfx_zeco2, sfx_zeco3, sfx_zeco4, sfx_zeco5, sfx_zeco6},
		  ["land"] = {sfx_zeco1, sfx_zeco2, sfx_zeco3, sfx_zeco4, sfx_zeco5, sfx_zeco6}
		},		
		["dirt"] = {
		  ["steps"] = {sfx_zedi1, sfx_zedi2, sfx_zedi3, sfx_zedi4, sfx_zedi5, sfx_zedi6},
		  ["land"] = {sfx_zedi1, sfx_zedi2, sfx_zedi3, sfx_zedi4, sfx_zedi5, sfx_zedi6}
		},
		["snow"] = {
		  ["steps"] = {sfx_zesa1, sfx_zesa2, sfx_zesa3, sfx_zesa4, sfx_zesa5},
		  ["land"] = {sfx_zesa1, sfx_zesa2, sfx_zesa3, sfx_zesa4, sfx_zesa5}
		},
		["cloth"] = {
		  ["steps"] = {sfx_zecl1, sfx_zecl2, sfx_zecl3, sfx_zecl4, sfx_zecl5},
		  ["land"] = {sfx_zecl1, sfx_zecl2, sfx_zecl3, sfx_zecl4, sfx_zecl5}
		},
		["sand"] = {
		  ["steps"] = {sfx_zedi1, sfx_zedi2, sfx_zedi3, sfx_zedi4, sfx_zedi5, sfx_zedi6},
		  ["land"] = {sfx_zedi1, sfx_zedi2, sfx_zedi3, sfx_zedi4, sfx_zedi5, sfx_zedi6}
		},			
		["wood_heavy"] = {
		  ["steps"] = {sfx_zewo1, sfx_zewo2, sfx_zewo3, sfx_zewo4, sfx_zewo5},
		  ["land"] = {sfx_zewo1, sfx_zewo2, sfx_zewo3, sfx_zewo4, sfx_zewo5}
		},
		["wood_light"] = {
		  ["steps"] = {sfx_zewo1, sfx_zewo2, sfx_zewo3, sfx_zewo4, sfx_zewo5},
		  ["land"] = {sfx_zewo1, sfx_zewo2, sfx_zewo3, sfx_zewo4, sfx_zewo5}
		},		
		["concrete"] = {
		  ["steps"] = {sfx_zeco1, sfx_zeco2, sfx_zeco3, sfx_zeco4, sfx_zeco5, sfx_zeco6},
		  ["land"] = {sfx_zeco1, sfx_zeco2, sfx_zeco3, sfx_zeco4, sfx_zeco5, sfx_zeco6}
		},
		["water"] = {
		  ["steps"] = {sfx_zewa1, sfx_zewa2, sfx_zewa3, sfx_zewa4},
		  ["land"] = {sfx_zewa1, sfx_zewa2, sfx_zewa3, sfx_zewa4}
		},
		["lava"] = {
		  ["steps"] = {sfx_zela1, sfx_zela2, sfx_zela3},
		  ["land"] = {sfx_zela1, sfx_zela2, sfx_zela3}
		},
		["glass"] = {
		  ["steps"] = {sfx_zegl1, sfx_zegl2},
		  ["land"] = {sfx_zegl1, sfx_zegl2}
		}
	},
	["minecraft"] = {
		["grass"] = {
		  ["steps"] = {sfx_migr1, sfx_migr2, sfx_migr3, sfx_migr4, sfx_migr5, sfx_migr6},
		  ["land"] = {sfx_migr1, sfx_migr2, sfx_migr3, sfx_migr4, sfx_migr5, sfx_migr6}
		},
		["metal_heavy"] = {
		  ["steps"] = {sfx_mico1, sfx_mico2, sfx_mico3, sfx_mico4, sfx_mico5, sfx_mico6},
		  ["land"] = {sfx_mico1, sfx_mico2, sfx_mico3, sfx_mico4, sfx_mico5, sfx_mico6}
		},
		["metal_light"] = {
		  ["steps"] = {sfx_mico1, sfx_mico2, sfx_mico3, sfx_mico4, sfx_mico5, sfx_mico6},
		  ["land"] = {sfx_mico1, sfx_mico2, sfx_mico3, sfx_mico4, sfx_mico5, sfx_mico6}
		},		
		["dirt"] = {
		  ["steps"] = {sfx_midi1, sfx_midi2, sfx_midi3, sfx_midi4},
		  ["land"] = {sfx_midi1, sfx_midi2, sfx_midi3, sfx_midi4}
		},
		["snow"] = {
		  ["steps"] = {sfx_misn1, sfx_misn2, sfx_misn3, sfx_misn4},
		  ["land"] = {sfx_misn1, sfx_misn2, sfx_misn3, sfx_misn4}
		},
		["cloth"] = {
		  ["steps"] = {sfx_micl1, sfx_micl2, sfx_micl3, sfx_micl4},
		  ["land"] = {sfx_micl1, sfx_micl2, sfx_micl3, sfx_micl4}
		},
		["sand"] = {
		  ["steps"] = {sfx_misa1, sfx_misa2, sfx_misa3, sfx_misa4, sfx_misa5},
		  ["land"] = {sfx_misa1, sfx_misa2, sfx_misa3, sfx_misa4, sfx_misa5}
		},			
		["wood_heavy"] = {
		  ["steps"] = {sfx_miwh1, sfx_miwh2, sfx_miwh3, sfx_miwh4, sfx_miwh5, sfx_miwh6},
		  ["land"] = {sfx_miwh1, sfx_miwh2, sfx_miwh3, sfx_miwh4, sfx_miwh5, sfx_miwh6}
		},
		["wood_light"] = {
		  ["steps"] = {sfx_miwl1, sfx_miwl2, sfx_miwl3, sfx_miwl4, sfx_miwl5, sfx_miwl6},
		  ["land"] = {sfx_miwl1, sfx_miwl2, sfx_miwl3, sfx_miwl4, sfx_miwl5, sfx_miwl6}
		},		
		["concrete"] = {
		  ["steps"] = {sfx_mico1, sfx_mico2, sfx_mico3, sfx_mico4, sfx_mico5, sfx_mico6},
		  ["land"] = {sfx_mico1, sfx_mico2, sfx_mico3, sfx_mico4, sfx_mico5, sfx_mico6}
		},
		["water"] = {
		  ["steps"] = {sfx_miwa1, sfx_miwa2, sfx_miwa3, sfx_miwa4},
		  ["land"] = {sfx_miwa1, sfx_miwa2, sfx_miwa3, sfx_miwa4}
		},
		["lava"] = {
		  ["steps"] = {sfx_mila1, sfx_mila2, sfx_mila3, sfx_mila4},
		  ["land"] = {sfx_mila1, sfx_mila2, sfx_mila3, sfx_mila4}
		},
		["glass"] = {
		  ["steps"] = {sfx_mico1, sfx_mico2, sfx_mico3, sfx_mico4, sfx_mico5, sfx_mico6},
		  ["land"] = {sfx_mico1, sfx_mico2, sfx_mico3, sfx_mico4, sfx_mico5, sfx_mico6}
		}
	}
}

for soundlist, soundinfo in pairs(soundinfolist)
	SoundListInfo[soundlist] = soundinfo
end

local flatsounds = { 
	["GFZROCKC"] = "concrete",
	["OLDGFZF1"] = "dirt",
	["OLDGFZF2"] = "grass",
	["OLDGFZF3"] = "grass",
	["OLDGFZF4"] = "concrete",
	["GFZROCKA"] = "concrete",
	["GFZWAVEF"] = "concrete",
	["GFZFNCG"] = "wood_heavy",
	["GFZFNCF"] = "wood_heavy",
	["GFZFLR01"] = "concrete",
	["GFZFLR02"] = "grass",
	["GFZFLR03"] = "metal_heavy",
	["GFZFLR04"] = "metal_heavy",
	["GFZFLR05"] = "wood_heavy",
	["GFZFLR06"] = "wood_heavy",
	["GFZFLR07"] = "wood_heavy",
	["GFZFLR08"] = "dirt",
	["GFZFLR09"] = "wood_heavy",
	["GFZFLR10"] = "grass",
	["GFZFLR11"] = "concrete",
	["GFZFLR12"] = "concrete",
	["GFZFLR13"] = "wood_heavy",
	["GFZFLR14"] = "concrete",
	["GFZFLR15"] = "concrete",
	["GFZFLR16"] = "concrete",
	["GFZFLR17"] = "concrete",
	["GFZFLR18"] = "wood_heavy",
	["GFZFLR19"] = "wood_heavy",
	["GFZFLR20"] = "concrete",
	["GFZFLR21"] = "grass",
	["GFZFLR22"] = "grass",
	["GFZROCK"] = "concrete",
	["GFZGRSW"] ="grass",
	["THCOMPF1"] = "metal_heavy",
	["THCOMPF2"] = "metal_heavy",
	["THCOMPF3"] = "metal_heavy",
	["THCOMPF4"] = "metal_heavy",
	["THCOMPF5"] = "metal_heavy",
	["THCOMPF6"] = "metal_heavy",
	["THZGRS1"] = "grass",
	["THZGRS2"] = "grass",
	["TH2_SF1"] = "concrete",
	["TH2_SF2"] = "concrete",
	["TH2_SF3"] = "concrete",
	["COMP7A"] = "metal_heavy",
	["COMP7B"] = "metal_heavy",
	["THZELA1"] = "metal_heavy",
	["THZELA2"] = "metal_heavy",
	["THZELB1"] = "metal_heavy",
	["THZELB2"] = "metal_heavy",
	["THZELC1"] = "metal_heavy",
	["THZELC2"] = "metal_heavy",
	["THZELD1"] = "metal_heavy",
	["THZELD2"] = "metal_heavy",
	["THZELE1"] = "metal_heavy",
	["THZELE2"] = "metal_heavy",
	["THZELF1"] = "metal_heavy",
	["THZELF2"] = "metal_heavy",
	["THZELG1"] = "metal_heavy",
	["THZELG2"] = "metal_heavy",
	["THZELH1"] = "metal_heavy",
	["THZELH2"] = "metal_heavy",
	["THZELI1"] = "metal_heavy",
	["THZELI2"] = "metal_heavy",
	["THZELJ1"] = "metal_heavy",
	["THZELJ2"] = "metal_heavy",
	["THZFLR35"] = "metal_heavy",
	["THZFLR36"] = "metal_heavy",
	["THZREDP1"] = "metal_heavy",
	["THZREDP2"] = "metal_heavy",
	["THZGRYP1"] = "metal_heavy",
	["THZGRYP2"] = "metal_heavy",
	["F_metal_heavy1"] = "metal_heavy",
	["F_metal_heavy2"] = "metal_heavy",
	["THZ2FN1"] = "concrete",
	["THZ3DPF1"] = "concrete",
	["THZ3DPF2"] = "concrete",
	["THZ3DPF3"] = "concrete",
	["THZ3DPF4"] = "concrete",
	["THZ3DPFA"] = "metal_heavy",
	["THZ3DPFB"] = "metal_heavy",
	["THZ3DPFC"] = "metal_heavy",
	["THZ3DPFD"] = "metal_heavy",
	["THPIPEF1"] = "metal_heavy",
	["THPIPEF2"] = "metal_heavy",
	["STKBOXS1"] = "metal_heavy",
	["STKBOXS2"] = "metal_heavy",
	["STKBOXS3"] = "metal_heavy",
	["STKBOXS4"] = "metal_heavy",
	["STKBOXT1"] = "metal_heavy",
	["STKBOXT2"] = "metal_heavy",
	["STKBOXT3"] = "metal_heavy",
	["STKBOXT4"] = "metal_heavy",
	["STKBOXK1"] = "metal_heavy",
	["STKBOXK2"] = "metal_heavy",
	["STKBOXK3"] = "metal_heavy",
	["STKBOXK4"] = "metal_heavy",
	["THZBOX"] = "metal_heavy",
	["THZBOXF1"] = "metal_heavy",
	["THZBOXF2"] = "metal_heavy",
	["THZBOXF3"] = "metal_heavy",
	["THZBOXF4"] = "metal_heavy",
	["THZFLR01"] = "metal_heavy",
	["THZFLR02"] = "metal_heavy",
	["THZFLR03"] = "metal_heavy",
	["THZFLR04"] = "metal_heavy",
	["THZFLR05"] = "metal_heavy",
	["THZFLR06"] = "metal_heavy",
	["THZFLR07"] = "metal_heavy",
	["THZFLR08"] = "metal_heavy",
	["THZFLR09"] = "metal_heavy",
	["THZFLR10"] = "metal_heavy",
	["THZFLR11"] = "metal_heavy",
	["THZFLR12"] = "metal_heavy",
	["THZFLR13"] = "metal_heavy",
	["THZFLR14"] = "metal_heavy",
	["THZFLR15"] = "metal_heavy",
	["THZFLR16"] = "metal_heavy",
	["THZFLR17"] = "metal_heavy",
	["THZFLR18"] = "metal_heavy",
	["THZFLR19"] = "metal_heavy",
	["THZFLR20"] = "metal_heavy",
	["THZFLR21"] = "metal_heavy",
	["THZFLR22"] = "metal_heavy",
	["THZFLR23"] = "metal_heavy",
	["THZFLR24"] = "metal_heavy",
	["THZFLR25"] = "metal_heavy",
	["THZFLR26"] = "metal_heavy",
	["THZFLR27"] = "metal_heavy",
	["THZFLR28"] = "metal_heavy",
	["THZFLR29"] = "metal_heavy",
	["THZFLR30"] = "concrete",
	["THZFLR31"] = "metal_heavy",
	["THZFLR32"] = "metal_heavy",
	["THZFLR33"] = "metal_heavy",
	["THZFLR34"] = "metal_heavy",
	["THZFLR35"] = "metal_heavy",
	["THZFLR36"] = "metal_heavy",
	["THZFLR37"] = "metal_heavy",
	["THZ2FN2"] = "metal_heavy",
	["THZ2FN3"] = "metal_heavy",
	["THZ2FN4"] = "metal_heavy",
	["THZ2FN4B"] = "metal_heavy",
	["THZ2FN5"] = "metal_heavy",
	["THZ2FN5B"] = "metal_heavy",
	["THZ2FN6"] = "metal_heavy",
	["THZ2FN6B"] = "metal_heavy",
	["THZ2FN7"] = "metal_heavy",
	["THZ2FN7B"] = "metal_heavy",
	["THZ2FN8"] = "metal_heavy",
	["THZ2FN9"] = "metal_heavy",
	["THZ2WN5"] = "metal_heavy",
	["THZ2WN5B"] = "metal_heavy",
	["THZ2WN6"] = "metal_heavy",
	["THZ2WN6B"] = "metal_heavy",
	["THZ2WN7"] = "metal_heavy",
	["THZ2WN7B"] = "metal_heavy",
	["THZ2WN8"] = "metal_heavy",
	["THZ2WN8B"] = "metal_heavy",
	["THZ2CN1"] = "metal_heavy",
	["THZ2CN1B"] = "metal_heavy",
	["THZ2CN2"] = "metal_heavy",
	["THZ2CN2B"] = "metal_heavy",
	["THZ2CN3"] = "metal_heavy",
	["THZ2CN3B"] = "metal_heavy",
	["THZ2CN4"] = "metal_heavy",
	["THZ2CN4B"] = "metal_heavy",
	["THZ2CN5"] = "metal_heavy",
	["THZ2CN5B"] = "metal_heavy",
	["THZ2CN6"] = "metal_heavy",
	["THZ2CN6B"] = "metal_heavy",
	["THZ2CN7"] = "metal_heavy",
	["THZ2CN7B"] = "metal_heavy",
	["THZ2CN8"] = "metal_heavy",
	["THZ2CN8B"] = "metal_heavy",
	["THZLIG1"] = "metal_heavy",
	["THZLIG2"] = "metal_heavy",
	["THZLITS"] = "metal_heavy",
	["THROCKF"] = "metal_heavy",
	["THROCKF"] = "concrete",
	["THROCKF2"] = "concrete",
	["THROCKLF"] = "concrete",
	["THTILEF1"] = "metal_heavy",
	["ALTBOXF1"] = "metal_heavy",
	["ALTBOXF2"] = "metal_heavy",
	["ALTBOXF3"] = "metal_heavy",
	["ALTBOXF4"] = "metal_heavy",
	["BOXWARN2"] = "metal_heavy",
	["BOXWARNG"] = "metal_heavy",
	["PIPE2F"] = "metal_heavy",
	["PIPE3F"] = "metal_heavy",
	["THDIRT"] = "dirt",
	["STEEL"] = "metal_heavy",
	["STEEL2"] = "metal_heavy",
	["STEEL3"] = "metal_heavy",
	["STEEL01"] = "metal_heavy",
	["STEEL02"] = "metal_heavy",
	["STEEL03"] = "metal_heavy",
	["STEEL04"] = "metal_heavy",
	["STEEL05"] = "metal_heavy",
	["STEEL06"] = "metal_heavy",
	["STEEL07"] = "metal_heavy",
	["STEEL08"] = "metal_heavy",
	["STEEL08B"] = "metal_heavy",
	["DSZ10"] = "concrete",
	["DSZ11"] = "concrete",
	["DSZFLR01"] = "concrete",
	["DSZFLR02"] = "concrete",
	["DSZFLR03"] = "concrete",
	["DSZFLR04"] = "dirt",
	["DSZFLR05"] = "dirt",
	["DSZFLR06"] = "dirt",
	["DSZFLR07"] = "concrete",
	["DSZFLR08"] = "concrete",
	["DSZFLR09"] = "concrete",
	["DSZFLR10"] = "concrete",
	["DSZFLR11"] = "concrete",
	["DSZFLR12"] = "concrete",
	["DSZFLR13"] = "concrete",
	["DSZFLR14"] = "concrete",
	["DSZFLR15"] = "concrete",
	["DSZFLR16"] = "concrete",
	["DSZFLR17"] = "concrete",
	["DSZFLR18"] = "concrete",
	["DSZFLR19"] = "concrete",
	["DSZRCKF1"] = "concrete",
	["DSZRCKF2"] = "concrete",
	["DSZRCKF3"] = "concrete",
	["DSWHEELF"] = "concrete",
	["DSBLOCK1"] = "concrete", 
	["DSBLOCK2"] = "concrete",
	["DSBLOCK3"] = "concrete", 
	["DSBLOCK4"] = "concrete",
	["DSCYAN1"] = "concrete",
	["DSCYAN3"] = "concrete",
	["DSDEBRIS"] = "concrete", 
	["DSFLOOR1"] = "concrete",
	["DSFLOOR2"] = "concrete",
	["DSKNUXB1"] = "concrete",
	["DSLTILE1"] = "concrete",
	["DSLTILE2"] = "concrete",
	["DSNOCLM2"] = "concrete",
	["DSRFLOR1"] = "concrete",
	["DSRFLOR2"] = "concrete",
	["DSROCK_1"] = "dirt",
	["DSROCK_2"] = "concrete",
	["DSSBFLR1"] = "dirt",
	["DSSBFLR2"] = "water",
	["DSSBFLR3"] = "water",
	["DSSBFLR4"] = "water",
	["DSSKSEA1"] = "water",
	["DSSKSEA2"] = "water",
	["DSSWIT1"] = "concrete",
	["DSSWIT2"] = "concrete",
	["DSSWIT3"] = "concrete",
	["DSSWIT4"] = "concrete",
	["DSSWIT5"] = "concrete",
	["DSSWIT6"] = "concrete",
	["DSTILEN1"] = "concrete",
	["DSTILE_1"] = "concrete",
	["DSTRACK1"] = "concrete",
	["DSTRACK2"] = "concrete",
	["DSWATER1"] = "water",
	["DSWATER2"] = "water",
	["CESTOND1"] = "concrete",
	["CESTOND2"] = "concrete",
	["CESTOND3"] = "concrete",
	["CESTOND4"] = "concrete",
	["CESTOND5"] = "concrete",
	["CESTOND6"] = "concrete",
	["CESTOND7"] = "concrete",
	["CESTOND8"] = "concrete",
	["CESTOND9"] = "concrete",
	["CESTONE"] = "concrete",
	["CESTONE1"] = "concrete",
	["CESTONE2"] = "concrete",
	["CESTONE3"] = "concrete",
	["CESTONE4"] = "concrete",
	["CESTONE5"] = "concrete",
	["CESTONE6"] = "concrete",
	["CESTONE7"] = "concrete",
	["CESTONE8"] = "concrete",
	["CESTONE9"] = "concrete",
	["BRIDGEA1"] = "concrete",
	["BRIDGEA2"] = "concrete",
	["BRIDGEA3"] = "concrete",
	["OLDCEZF1"] = "concrete",
	["CEBRAMBL"] = "grass",
	["CEZFLR01"] = "concrete",
	["CEZFLR02"] = "grass",
	["CEZFLR03"] = "grass",
	["CEZFLR04"] = "concrete",
	["CEZFLR05"] = "grass",
	["CEZFLR06"] = "concrete",
	["CEZFLR07"] = "wood_heavy",
	["CEZFLR08"] = "wood_heavy",
	["CEZFLR09"] = "concrete",
	["CEZFLR10"] = "wood_heavy",
	["CEZFLR11"] = "wood_heavy",
	["CEZFLR12"] = "grass",
	["CEZFLR13"] = "grass",
	["CEZROCKA"] = "concrete",
	["CEZDRTF0"] = "dirt",
	["CEZGRS0"] = "grass",
	["CEZGRS1"] = "grass",
	["CEZGRS2"] = "dirt",
	["CEZLEAF0"] = "grass",
	["CEZRCKF0"] = "concrete",
	["LIBFLR1"] = "wood_heavy",
	["LIBFLR2"] = "wood_heavy",
	["DMAFLAT1"] = "concrete",
	["DMAFLAT2"] = "concrete",
	["DMAFLAT3"] = "concrete",
	["DMAFLAT4"] = "concrete",
	["DMAFLAT5"] = "concrete",
	["DMAFLAT6"] = "concrete",
	["DMAFLAT7"] = "concrete",
	["DMAFLAT8"] = "concrete",
	["CETILE1"] = "concrete",
	["CETILE1B"] = "concrete",
	["CETILE2"] = "concrete",
	["CETILE2B"] = "concrete",
	["CETILE3"] = "concrete",
	["CETILD1"] = "concrete",
	["CETILD1B"] = "concrete",
	["CETILD2"] = "concrete",
	["CETILD2B"] = "concrete",
	["CETILD3"] = "concrete",
	["CETILC1"] = "concrete",
	["CETILC2"] = "concrete",
	["CETILB1"] = "concrete",
	["CETILB1B"] = "concrete",
	["CETILB2"] = "concrete",
	["CETILB2B"] = "concrete",
	["CETILB3"] = "concrete",
	["CASTLE2"] = "wood_heavy",
	["CASTLE3"] = "wood_heavy",
	["CASTLE4"] = "wood_heavy",
	["CASTLE5"] = "wood_heavy",
	["CASTLED"] = "wood_heavy",
	["CASTLEF"] = "wood_heavy",
	["CASTLEG"] = "wood_heavy",
	["CASTLEE"] = "wood_heavy",
	["CASTLEFF"] = "metal_light",
	["CEZBRWL1"] = "dirt",
	["CESBCA00"] = "concrete",
	["CESBFO01"] = "concrete",
	["CEBURST1"] = "concrete",
	["CEBURST2"] = "concrete",
	["CEBURST3"] = "concrete",
	["CEVBARF"] = "grass",
	["CESTP1E"] = "concrete",
	["CESTP1N"] = "concrete",
	["CESTP1W"] = "concrete",
	["CESTP1S"] = "concrete",
	["CECRPTR"] = "cloth",
	["CECRPTRE"] = "cloth",
	["CECRPTRS"] = "cloth",
	["CECRPTRW"] = "cloth",
	["CECRPTRN"] = "cloth",
	["CECRPTG1"] = "cloth",
	["CECRPTG2"] = "cloth",
	["CECRPTGN"] = "cloth",
	["CECRPTGS"] = "cloth",
	["CECRPTGW"] = "cloth",
	["CECRPTGE"] = "cloth",
	["CECRPTB"] = "cloth",
	["CECRPTBE"] = "cloth",
	["CECRPTBS"] = "cloth",
	["CECRPTBW"] = "cloth",
	["CECRPTBN"] = "cloth",
	["CETILL1"] = "concrete",
	["CETILL1B"] = "concrete",
	["CETILL2"] = "concrete",
	["CETILL2B"] = "concrete",
	["CETILL3"] = "concrete",
	["CETILL4"] = "concrete",
	["CETILL5"] = "concrete",
	["CETILL6"] = "concrete",
	["CEZCLOUD"] = "concrete",
	["CEZGRS10"] = "grass",
	["CEZGRS11"] = "grass",
	["CEZPLD1F"] = "dirt",
	["CEZWATR0"] = "water",
	["CEZWATR1"] = "water",
	["SLF_174"] = "concrete",
	["CETILE4"] = "concrete",
	["CETILE4B"] = "concrete",
	["CETILC4"] = "concrete",
	["CETILC4B"] = "concrete",
	["CEBUSTC1"] = "concrete",
	["CESTOND3"] = "concrete",
	["ACZWAL2"] = "concrete",
	["AC2_8_2_"] = "concrete",
	["ACDEBRIS"] = "metal_heavy",
	["ACDEBRI2"] = "metal_heavy",
	["ACMTRKF1"] = "wood_heavy",
	["ACROAD1"] = "concrete",
	["ACSBCAN1"] = "concrete",
	["ACSBCAN3"] = "concrete",
	["ACSBDSRC"] = "dirt",
	["ACSBDSRR"] = "wood_heavy",
	["ACSBDSRT"] = "dirt",
	["ACSTEAM0"] = "metal_heavy",
	["ACROCKY1"] = "concrete",
	["ACROCKY2"] = "concrete",
	["ACROCKY3"] = "concrete",
	["ACROCKY4"] = "concrete",
	["ACROCKY5"] = "concrete",
	["ACROPE1"] = "dirt",
	["ACROPE2"] = "dirt",
	["ACROPF1"] = "concrete",
	["ACROPF2"] = "concrete",
	["ACROPF3"] = "concrete",
	["ACROPF4"] = "concrete",
	["ACZBARLF"] = "metal_heavy",
	["ACZCRATF"] = "wood_heavy",
	["ACZFLR01"] = "concrete",
	["ACZFLR02"] = "concrete",
	["ACZFLR03"] = "concrete",
	["ACZFLR04"] = "wood_heavy",
	["ACZFLR05"] = "wood_heavy",
	["ACZFLR06"] = "wood_heavy",
	["ACZFLR07"] = "wood_heavy",
	["ACZFLR08"] = "wood_heavy",
	["ACZFLR09"] = "wood_heavy",
	["ACZFLR10"] = "wood_heavy",
	["ACZFLR11"] = "wood_heavy",
	["ACZFLR12"] = "metal_heavy",
	["ACZFLR13"] = "metal_heavy",
	["ACZFLR14"] = "cloth",
	["ACZFLR15"] = "cloth",
	["ACZFLR16"] = "wood_heavy",
	["ACZFLR17"] = "wood_heavy",
	["ACZFLR18"] = "wood_heavy",
	["ACZFLR19"] = "wood_heavy",
	["ACZFLR20"] = "concrete",
	["ACZFLR21"] = "concrete",
	["ACZFLR22"] = "cloth",
	["ACZFLR23"] = "cloth",
	["ACZFLR24"] = "concrete",
	["ACZFLR25"] = "concrete",
	["ACZFLR26"] = "concrete",
	["ACZFLR27"] = "concrete",
	["ACZFLR28"] = "concrete",
	["ACZRAILF"] = "metal_heavy",
	["ACZRAILP"] = "concrete",
	["ACZRFL1A"] = "concrete",
	["ACZRFL1B"] = "concrete",
	["ACZRFL1C"] = "concrete",
	["ACZRFL1D"] = "concrete",
	["ACZRFL1E"] = "concrete",
	["ACZRFL1F"] = "concrete",
	["ACZRFL1G"] = "concrete",
	["ACZRFL1H"] = "concrete",
	["ACZRFL2A"] = "concrete",	
	["ACZRFL2B"] = "concrete",
	["ACZRFL2C"] = "concrete",
	["ACZRFL2D"] = "concrete",
	["ACZRFL2E"] = "concrete",
	["ACZRFL2F"] = "concrete",
	["ACZRFL2G"] = "concrete",
	["ACZRFL2H"] = "concrete",	
	["ACZROKF1"] = "concrete",
	["ACZROKF2"] = "concrete",
	["ACZROCK3"] = "concrete",
	["ACWOODS1"] = "wood_heavy",
	["ACWOODS2"] = "wood_heavy",
	["ACWOOD1F"] = "wood_heavy",
	["ACWOOD2F"] = "wood_heavy",
	["ACWOOD3F"] = "wood_heavy",
	["ACWOOD4F"] = "wood_heavy",
	["ACWOODBX"] = "wood_heavy",
	["FACSB_3"] = "dirt",
	["FACSB_4"] = "grass",
	["RVZWALF1"] = "concrete",
	["RVZWALF2"] = "concrete",
	["RVZWALF3"] = "concrete",
	["RVZWALF4"] = "concrete",
	["RVZWALF5"] = "concrete",
	["RVZWALF6"] = "concrete",
	["RVZWALF7"] = "concrete",
	["MMFLR7"] = "concrete",
	["MMFLR8"] = "concrete",
	["MMFLR9"] = "concrete",
	["MMFLRA"] = "concrete",
	["MMFLRB2"] = "concrete",
	["MMFLRB3"] = "concrete",
	["MMFLRB4"] = "concrete",
	["MMFLRB5"] = "concrete",
	["MMFLRB5A"] = "concrete",
	["MMFLRB6"] = "concrete",
	["MMFLRB7"] = "concrete",
	["MMFLRB8"] = "concrete",
	["MMFLRD"] = "concrete",
	["MMFLRE"] = "concrete",
	["MMFLRF"] = "concrete",
	["FLOOR6_2"] = "concrete",
	["MINECRAT"] = "concrete",
	["TLITE6_1"] = "concrete",
	["TLITE6_5"] = "concrete",
	["TLITE6_6"] = "concrete",
	["RVZDRUMT"] = "concrete",
	["RVZGRS01"] = "grass",
	["RVZGRS02"] = "grass",
	["RVZGRS03"] = "grass",
	["RVZGRS04"] = "grass",
	["RVZGRS05"] = "grass",
	["RVZGRS06"] = "grass",
	["RVZGRS07"] = "grass",
	["RVZ2STOP"] = "concrete",
	["RVZ2SBTM"] = "concrete",
	["RVZ1SBTM"] = "concrete",
	["FRSTRCKF"] = "concrete",
	["MMBFLR9"] = "concrete",
	["MMBFLRA"] = "concrete",
	["MMBFLRB"] = "concrete",
	["MMBFLRC"] = "concrete",
	["RVDARKF1"] = "concrete",
	["RVDARKF2"] = "concrete",
	["RVPUMICF"] = "concrete",
	["RVRCKTTO"] = "concrete",
	["RVZ1S_BF"] = "lava",
	["ERZBGF3"] = "metal_heavy",
	["EGRIDF1"] = "metal_heavy",
	["EGRIDF2"] = "metal_heavy",
	["EGRIDF3"] = "metal_heavy",
	["ERZBGF2"] = "metal_heavy",
	["ERZBGF5"] = "metal_heavy",
	["ERZBGF6"] = "metal_heavy",
	["ERZBLUF2"] = "metal_heavy",
	["ERZBLUF3"] = "metal_heavy",
	["ERZBLUF4"] = "metal_heavy",
	["ERZFAN1"] = "metal_heavy",
	["ERZFAN2"] = "metal_heavy",
	["ERZFAN3"] = "metal_heavy",
	["ERZFAN4"] = "metal_heavy",
	["ERZFANR1"] = "metal_heavy",
	["ERZFANR2"] = "metal_heavy",
	["ERZFANR3"] = "metal_heavy",
	["ERZFANR4"] = "metal_heavy",
	["ERZFLR00"] = "metal_heavy",
	["ERZFLR01"] = "metal_heavy",
	["ERZFLR02"] = "metal_heavy",
	["ERZFLR03"] = "metal_heavy",
	["ERZFLR04"] = "metal_heavy",
	["ERZFLR05"] = "metal_heavy",
	["ERZFLR06"] = "metal_heavy",
	["ERZFLR07"] = "metal_heavy",
	["ERZFLR08"] = "metal_heavy",
	["ERZFLR09"] = "metal_heavy",
	["ERZFLR10"] = "metal_heavy",
	["ERZFLR11"] = "metal_heavy",
	["ERZGREYF"] = "metal_heavy",
	["ERZGRYF2"] = "metal_heavy",
	["ERZGRYF3"] = "metal_heavy",
	["ERZGRYF4"] = "metal_heavy",
	["ERZMASH1"] = "metal_heavy",
	["ERZMASH2"] = "metal_heavy",
	["ERZMASH3"] = "metal_heavy",
	["ERZMASH4"] = "metal_heavy",
	["ERZMASH5"] = "metal_heavy",
	["ERZMASH6"] = "metal_heavy",
	["ERZMASH7"] = "metal_heavy",
	["ERZMASH8"] = "metal_heavy",
	["ERZPLTF1"] = "metal_heavy",
	["ERZPLTF2"] = "metal_heavy",
	["ERZPLTF3"] = "metal_heavy",
	["ERZPLTF4"] = "metal_heavy",
	["ERZPLTF5"] = "metal_heavy",
	["ERZPLTF6"] = "metal_heavy",
	["ERZRCKF1"] = "concrete",
	["ERZRCKF2"] = "concrete",
	["ERZRCKF3"] = "concrete",
	["ERZRCKF4"] = "concrete",
	["ERZRCKF5"] = "concrete",
	["ERZRCKF6"] = "dirt",
	["ERZRCKF7"] = "concrete",
	["ERZRCKF8"] = "concrete",
	["ERZRCKF9"] = "concrete",
	["ERZREDF2"] = "metal_heavy",
	["ERZREDF3"] = "metal_heavy",
	["ERZREDF4"] = "metal_heavy",
	["ERZREDF5"] = "metal_heavy",
	["ERFANFL1"] = "metal_heavy",
	["ERFANFL2"] = "metal_heavy",
	["ERFANFL3"] = "metal_heavy",
	["ERLAVA1"] = "lava", 
	["ERZFLR13"] = "metal_heavy",
	["ERZFLR14"] = "metal_heavy",
	["ERZRCKF7"] = "dirt",
	["ERZAI200"] = "concrete",
	["ERZAI201"] = "concrete",
	["ERZAI202"] = "concrete",
	["ERZAI203"] = "concrete",
	["ERZAI204"] = "concrete",
	["ERZAI205"] = "concrete",
	["ERZAI206"] = "concrete",
	["ERZAI207"] = "concrete",
	["ERZAI208"] = "concrete",
	["ERZAI209"] = "concrete",
	["ERZAI210"] = "concrete",
	["ERZAI211"] = "concrete",
	["ERZAI212"] = "concrete",
	["ERZAI213"] = "concrete",
	["ERZAI214"] = "concrete",
	["ERZAI215"] = "concrete",
	["ERZAIR00"] = "concrete",
	["ERZAIR01"] = "concrete",
	["ERZAIR02"] = "concrete",
	["ERZAIR03"] = "concrete",
	["ERZAIR04"] = "concrete",
	["ERZAIR05"] = "concrete",
	["ERZAIR06"] = "concrete",
	["ERZAIR07"] = "concrete",
	["ERZAIR08"] = "concrete",
	["ERZAIR09"] = "concrete",
	["ERZAIR10"] = "concrete",
	["ERZAIR11"] = "concrete",
	["ERZAIR12"] = "concrete",
	["ERZAIR13"] = "concrete",
	["ERZAIR14"] = "concrete",
	["ERZAIR15"] = "concrete",
	["ERZBGF1"] = "metal_heavy",
	["ERZBGF4"] = "metal_heavy",
	["ERZBLUF1"] = "metal_heavy",
	["ERZBLUF5"] = "metal_heavy",
	["ERZCRTF1"] = "metal_heavy",
	["ERZFLR12"] = "metal_heavy",
	["ERZGRYF1"] = "metal_heavy",
	["ERZLITF2"] = "metal_heavy",
	["ERZPI2F1"] = "metal_heavy",
	["ERZPIPF1"] = "metal_heavy",
	["ERZPIPF2"] = "metal_heavy",
	["ERZPIPF5"] = "metal_heavy",
	["ERZPIPF6"] = "metal_heavy",
	["ERZPIPF8"] = "metal_heavy",
	["ERZREDF1"] = "metal_heavy",
	["ERZPIPF3"] = "metal_heavy",
	["ERZPIPF9"] = "metal_heavy",
	["ERZGRYF5"] = "metal_heavy",
	["ERZGRTF1"] = "metal_heavy",
	["ERZWRNF1"] = "metal_heavy",
	["DCZFLR01"] = "concrete",
	["DCZFLR02"] = "metal_heavy",
	["DCZFLR03"] = "concrete",
	["DCZFLR04"] = "concrete",
	["DCZFLR05"] = "concrete",
	["DCZFLR06"] = "concrete",
	["DCZFLR07"] = "metal_heavy",
	["DCZFLR08"] = "metal_heavy",
	["DCZFLR09"] = "concrete",
	["DCZFLR10"] = "sand",
	["DCZFLR11"] = "metal_heavy",
	["DCZFLR12"] = "metal_heavy",
	["DCZFLR13"] = "concrete",
	["DCZFLR14"] = "concrete",
	["DCZFLR15"] = "concrete",
	["DCZFLR16"] = "concrete",
	["DCZFLR17"] = "concrete",
	["DCFLR01"] = "concrete",
	["DCFLR02"] = "concrete",
	["DCFLR03"] = "concrete",
	["DCFLR04"] = "concrete",
	["DCFLR05"] = "concrete",
	["DCFLR06"] = "concrete",
	["DCFLR07"] = "concrete",
	["DCFLR08"] = "concrete",
	["DCFLR09"] = "concrete",
	["DCFLR10"] = "concrete",
	["DCFLR11"] = "concrete",
	["DCFLR12"] = "concrete",
	["DCFLR13"] = "concrete",
	["DCFLR14"] = "concrete",
	["DCFLR15"] = "concrete",
	["DCFLR16"] = "concrete",
	["DCFLR17"] = "concrete",
	["DCFLR18"] = "concrete",
	["DCFLR19"] = "concrete",
	["DCFLR20"] = "concrete",
	["DCFLR21"] = "concrete",
	["DCFLR22"] = "concrete",
	["DCFLR23"] = "concrete",
	["DCFLR24"] = "concrete",
	["DCFLR25"] = "concrete",
	["DCZGRASS"] = "grass",
	["DSHIPF1"] = "metal_heavy",
	["DSHIPF2"] = "metal_heavy",
	["DSHIPF3"] = "metal_heavy",
	["DSHIPF4"] = "metal_heavy",
	["DSHIPF5"] = "metal_heavy",
	["DSHIPF6"] = "metal_heavy",
	["DSHIPF7"] = "metal_heavy",
	["DSHIPF8"] = "metal_heavy",
	["DSHIPF9"] = "metal_heavy",
	["DSHIPFA"] = "metal_heavy",
	["DSHIPFB"] = "metal_heavy",
	["DSHIPFC"] = "metal_heavy",
	["DSHIPFD"] = "metal_heavy",
	["DSHIPFE"] = "metal_heavy",
	["LFLRA1"] = "concrete",
	["LFLRA2"] = "concrete",
	["LFLRA3"] = "concrete",
	["LFLRB1"] = "concrete",
	["LFLRB2"] = "concrete",
	["LFLRB3"] = "concrete",
	["LFLRB4"] = "concrete",
	["LFLRC1"] = "concrete",
	["LFLRC2"] = "concrete",
	["LFLRC3"] = "concrete",
	["LFLRC4"] = "concrete",
	["LFLRD1"] = "concrete",
	["LFLRD2"] = "concrete",	
	["LFLRE1"] = "concrete",
	["LFLRE2"] = "concrete",
	["LFLRF1"] = "concrete",
	["LFLRF1B"] = "concrete",
	["LFLRF2"] = "concrete",
	["LFLRF2B"] = "concrete",
	["LFLRF3"] = "concrete",
	["LFLRF4"] = "concrete",
	["GHZBRDG1"] = "wood_heavy",
	["GHZBRDG2"] = "wood_heavy",
	["GHZBRDG3"] = "wood_heavy",
	["GHZBRDG4"] = "wood_heavy",
	["GHZFLR02"] = "wood_heavy",
	["GHZFLR07"] = "concrete",
	["GHZFLR08"] = "concrete",
	["GHZFLR09"] = "wood_heavy",
	["GHZFLR0C"] = "concrete",
	["GHZROCKF"] = "concrete",
	["GRNLITE1"] = "concrete",
	["GATE2"] = "concrete",
	["2FORTF1"] = "wood_heavy",
	["2FORTF2"] = "wood_heavy",
	["2FORTF3"] = "wood_light",
	["2FORTF4"] = "wood_light",
	["2FORTF5"] = "wood_heavy",
	["2FORTF6"] = "wood_heavy",
	["2FORTF7"] = "wood_heavy",
	["2FORTF8"] = "wood_heavy",
	["2FORTF9"] = "wood_heavy",
	["2FORTFA"] = "wood_heavy",
	["2FORTFB"] = "concrete",
	["2FORTFC"] = "concrete",
	["WHITEFLR"] = "concrete",
	["LIMEFLR"] = "concrete",
	["BLUEFLR"] = "concrete",
	["CYANFLR"] = "concrete",
	["GREENFLR"] = "concrete",
	["GREYFLR"] = "concrete",
	["GOLDFLR"] = "concrete",
	["NEOGFLR"] = "concrete",
	["ORGFLR"] = "concrete",
	["VIOFLR"] = "concrete",
	["PURFLR"] = "concrete",
	["REDFLR"] = "concrete",
	["YELFLR"] = "concrete",
	["STLBLKF1"] = "metal_heavy",
	["STLBLKF2"] = "metal_heavy",
	["STLFLR01"] = "metal_heavy",
	["STLFLR02"] = "metal_heavy",
	["HPZBLOK"] = "concrete",
	["HPZROCK"] = "concrete",
	["MARIOF1"] = "concrete",
	["MARIOF2"] = "concrete",
	["MARIOF3"] = "metal_heavy",
	["MARIOF4"] = "concrete",
	["MARIOF5"] = "concrete",
	["MARIOF5A"] = "concrete",
	["MARIOF6"] = "metal_heavy",
	["MARIOF7"] = "concrete",
	["MARIOF8"] = "concrete",
	["MARIOF9"] = "concrete",
	["MARIOF10"] = "concrete",
	["MARIOF11"] = "concrete",
	["MARIOF12"] = "concrete",
	["MARIOF13"] = "concrete",
	["MARIOF14"] = "concrete",
	["MARIOF15"] = "concrete",
	["MARIOF16"] = "concrete",
	["MARROCK1"] = "concrete",
	["MARROCK2"] = "concrete",
	["MARROCK3"] = "concrete",
	["MARROCK4"] = "concrete",
	["THWOMPFL"] = "concrete",
	["GSPECF"] = "concrete",
	["GSPECF2"] = "concrete",
	["GSPECF3"] = "concrete",
	["PSPECF"] = "concrete",
	["PSPECF2"] = "concrete",
	["PSPECF3"] = "concrete",
	["BSPECF"] = "concrete",
	["BSPECF2"] = "concrete",
	["BSPECF3"] = "concrete",
	["CSPECF"] = "concrete",
	["CSPECF2"] = "concrete",
	["CSPECF3"] = "concrete",
	["YSPECF"] = "concrete",
	["YSPECF2"] = "concrete",
	["YSPECF3"] = "concrete",
	["RSPECF"] = "concrete",
	["RSPECF2"] = "concrete",
	["RSPECF3"] = "concrete",
	["ASPECF"] = "concrete",
	["ASPECF2"] = "concrete",
	["ASPECF3"] = "concrete",
	["SFLR01"] = "concrete",
	["SFLR01B"] = "concrete",
	["SFLR02"] = "concrete",
	["SFLR02B"] = "concrete",
	["SFLR03"] = "concrete",
	["SFLR04"] = "concrete",
	["SFLR05"] = "concrete",
	["SFLR06"] = "concrete",
	["SFLR07"] = "concrete",
	["SFLR08"] = "concrete",
	["SFLR09"] = "concrete",
	["SFLR10"] = "concrete",
	["SFLR11"] = "concrete",
	["SFLR12"] = "concrete",
	["SFLR13"] = "concrete",
	["SFLR14"] = "concrete",
	["SFLR15"] = "concrete",
	["SFLR16"] = "concrete",
	["SFLR17"] = "concrete",
	["SFLR18"] = "concrete",
	["SFLR19"] = "concrete",
	["SFLR20"] = "concrete",
	["SFLR21"] = "concrete",
	["SFLR22"] = "concrete",
	["SFLR23"] = "concrete",
	["SFLR24"] = "concrete",
	["SFLR25"] = "concrete",
	["SFLR26"] = "concrete",
	["SFLR27"] = "concrete",
	["SFLR28"] = "concrete",
	["SFLR29"] = "concrete",
	["SFLR30"] = "concrete",
	["SFLR31"] = "concrete",
	["SFLR32"] = "concrete",
	["SFLR33"] = "concrete",
	["SFLR34"] = "concrete",
	["SFLR35"] = "concrete",
	["SPACEBL"] = "concrete",
	["SPACEBM"] = "concrete",
	["SPACEBS"] = "concrete",
	["SPACEGL"] = "concrete",
	["SPACEGM"] = "concrete",
	["SPACEGS"] = "concrete",
	["SPACERL"] = "concrete",
	["SPACERM"] = "concrete",
	["SPACERS"] = "concrete",
	["DSBLOCB1"] = "concrete",
	["GFZFWR01"] = "grass",
	["GFZFWR02"] = "grass",
	["THPIPEFA"] = "concrete",
	["THPIPEFB"] = "concrete",
	["THPIPEFC"] = "concrete",
	["THPIPEFD"] = "concrete",
	["BWATER01"] = "water",
	["BWATER02"] = "water",
	["BWATER03"] = "water",
	["BWATER04"] = "water",
	["BWATER05"] = "water",
	["BWATER06"] = "water",
	["BWATER07"] = "water",
	["BWATER08"] = "water",
	["BWATER09"] = "water",
	["BWATER10"] = "water",
	["BWATER11"] = "water",
	["BWATER12"] = "water",
	["BWATER13"] = "water",
	["BWATER14"] = "water",
	["BWATER15"] = "water",
	["BWATER16"] = "water",
	["FWATER1"] = "water",
	["FWATER2"] = "water",
	["FWATER3"] = "water",
	["FWATER4"] = "water",
	["FWATER5"] = "water",
	["FWATER6"] = "water",
	["FWATER7"] = "water",
	["FWATER8"] = "water",
	["FWATER9"] = "water",
	["FWATER10"] = "water",
	["FWATER11"] = "water",
	["FWATER12"] = "water",
	["FWATER13"] = "water",
	["FWATER14"] = "water",
	["FWATER15"] = "water",
	["FWATER16"] = "water",
	["CHEMG01"] = "water",
	["CHEMG02"] = "water",
	["CHEMG03"] = "water",
	["CHEMG04"] = "water",
	["CHEMG05"] = "water",
	["CHEMG06"] = "water",
	["CHEMG07"] = "water",
	["CHEMG08"] = "water",
	["CHEMG09"] = "water",
	["CHEMG10"] = "water",
	["CHEMG11"] = "water",
	["CHEMG12"] = "water",
	["CHEMG13"] = "water",
	["CHEMG14"] = "water",
	["CHEMG15"] = "water",
	["CHEMG16"] = "water",
	["GWATER01"] = "water",
	["GWATER02"] = "water",
	["GWATER03"] = "water",
	["GWATER04"] = "water",
	["GWATER05"] = "water",
	["GWATER06"] = "water",
	["GWATER07"] = "water",
	["GWATER08"] = "water",
	["GWATER09"] = "water",
	["GWATER10"] = "water",
	["GWATER11"] = "water",
	["GWATER12"] = "water",
	["GWATER13"] = "water",
	["GWATER14"] = "water",
	["GWATER15"] = "water",
	["GWATER16"] = "water",
	["GOOP01"] = "water",
	["GOOP02"] = "water",
	["GOOP03"] = "water",
	["GOOP04"] = "water",
	["GOOP05"] = "water",
	["GOOP06"] = "water",
	["GOOP07"] = "water",
	["GOOP08"] = "water",
	["GOOP09"] = "water",
	["GOOP10"] = "water",
	["GOOP11"] = "water",
	["GOOP12"] = "water",
	["GOOP13"] = "water",
	["GOOP14"] = "water",
	["GOOP15"] = "water",
	["GOOP16"] = "water",
	["LWATER1"] = "water",
	["LWATER2"] = "water",
	["LWATER3"] = "water",
	["LWATER4"] = "water",
	["LWATER5"] = "water",
	["LWATER6"] = "water",
	["LWATER7"] = "water",
	["LWATER8"] = "water",
	["LWATER9"] = "water",
	["LWATER10"] = "water",
	["LWATER11"] = "water",
	["LWATER12"] = "water",
	["LWATER13"] = "water",
	["LWATER14"] = "water",
	["LWATER15"] = "water",
	["LWATER16"] = "water",
	["TAR"] = "lava",
	["OIL01"] = "water",
	["OIL02"] = "water",
	["OIL03"] = "water",
	["OIL04"] = "water",
	["OIL05"] = "water",
	["OIL06"] = "water",
	["OIL07"] = "water",
	["OIL08"] = "water",
	["OIL09"] = "water",
	["OIL10"] = "water",
	["OIL11"] = "water",
	["OIL12"] = "water",
	["OIL13"] = "water",
	["OIL14"] = "water",
	["OIL15"] = "water",
	["OIL16"] = "water",
	["LAVA1"] = "lava",
	["LAVA2"] = "lava",
	["LAVA3"] = "lava",
	["LAVA4"] = "lava",
	["RLAVA1"] = "lava",
	["RLAVA2"] = "lava",
	["RLAVA3"] = "lava",
	["RLAVA4"] = "lava",
	["RLAVA5"] = "lava",
	["RLAVA6"] = "lava",
	["RLAVA7"] = "lava",
	["RLAVA8"] = "lava",
	["SURF01"] = "water",
	["SURF02"] = "water",
	["SURF03"] = "water",
	["SURF04"] = "water",
	["SURF05"] = "water",
	["SURF06"] = "water",
	["SURF07"] = "water",
	["SURF08"] = "water",
	["WATER0"] = "water",
	["WATER1"] = "water",
	["WATER2"] = "water",
	["WATER3"] = "water",
	["WATER4"] = "water",
	["WATER5"] = "water",
	["WATER6"] = "water",
	["WATER7"] = "water",
	["SICK01"] = "water",
	["SICK02"] = "water",
	["SICK03"] = "water",
	["SICK04"] = "water",
	["SICK05"] = "water",
	["SICK06"] = "water",
	["SICK07"] = "water",
	["SICK08"] = "water",
	["SICK09"] = "water",
	["SICK10"] = "water",
	["SICK11"] = "water",
	["SICK12"] = "water",
	["SICK13"] = "water",
	["SICK14"] = "water",
	["SICK15"] = "water",
	["SICK16"] = "water",
	["HHWATR01"] = "water",
	["HHWATR02"] = "water",
	["HHWATR03"] = "water",
	["HHWATR04"] = "water",
	["HHWATR05"] = "water",
	["HHWATR06"] = "water",
	["HHWATR07"] = "water",
	["HHWATR08"] = "water",
	["HHWATR09"] = "water",
	["HHWATR10"] = "water",
	["HHWATR11"] = "water",
	["HHWATR12"] = "water",
	["HHWATR13"] = "water",
	["HHWATR14"] = "water",
	["HHWATR15"] = "water",
	["HHWATR16"] = "water",
	["CLIFF1"] = "concrete",
	["CLIFF2"] = "concrete",
	["CLIFF3"] = "concrete",
	["CLIFF4"] = "concrete",
	["CLIFF5"] = "concrete",
	["CLIFF6"] = "concrete",
	["CLIFF7"] = "concrete",
	["CLIFF8"] = "concrete",
	["CLIFF9"] = "concrete",
	["CLIFFA"] = "concrete",
	["CLIFFB"] = "concrete",
	["CLIFFC"] = "concrete",
	["CLIFFD"] = "concrete",
	["CLIFF1S"] = "concrete",
	["CLIFF2S"] = "concrete",
	["CLIFF3S"] = "concrete",
	["CLIFF4S"] = "concrete",
	["CLIFF5S"] = "concrete",
	["CLIFF6S"] = "concrete",
	["CLIFF7S"] = "concrete",
	["CLIFF8S"] = "concrete",
	["CLIFF9S"] = "concrete",
	["CLIFFAS"] = "concrete",
	["CLIFFBS"] = "concrete",
	["CLIFFCS"] = "concrete",
	["CLIFFDS"] = "concrete",
	["CLIFFE"] = "concrete",
	["CLIFFES"] = "concrete",
	["CLIFFF"] = "concrete",
	["CLIFFFS"] = "concrete",
	["CLIFFG"] = "concrete",
	["CLIFFGS"] = "concrete",
	["CLIFFH"] = "concrete",
	["CLIFFHS"] = "concrete",
	["JNGF13S"] = "concrete",
	["JNGF14S"] = "concrete",
	["JNGF15S"] = "concrete",
	["JNGF16S"] = "concrete",
	["JNGFLR01"] = "concrete",
	["JNGFLR02"] = "concrete",
	["JNGFLR03"] = "concrete",
	["JNGFLR04"] = "concrete",
	["JNGFLR05"] = "wood_heavy",
	["JNGFLR06"] = "wood_heavy",
	["JNGFLR07"] = "wood_heavy",
	["JNGFLR08"] = "wood_heavy",
	["JNGFLR09"] = "grass",
	["JNGFLR10"] = "grass",
	["JNGFLR11"] = "grass",
	["JNGFLR12"] = "grass",
	["JNGFLR13"] = "concrete",
	["JNGFLR14"] = "concrete",
	["JNGFLR15"] = "concrete",
	["JNGFLR16"] = "concrete",
	["JNGGRS01"] = "grass",
	["JNGGRS02"] = "grass",
	["JNGGRS03"] = "grass",
	["JNGGRS04"] = "grass",
	["JNGGRS05"] = "grass",
	["JNGGRS06"] = "grass",
	["JNGGRS07"] = "grass",
	["JNGGRS08"] = "grass",
	["JNGGRS09"] = "grass",
	["JNGGRS10"] = "grass",
	["JNGGRS11"] = "grass",
	["JNGGRS12"] = "grass",
	["JNGMUDF1"] = "dirt",
	["JNGMUDF2"] = "dirt",
	["JNGMUDF3"] = "dirt",
	["JNGMUDF4"] = "dirt",
	["JNGMUDF5"] = "dirt",
	["JNGRCKF1"] = "concrete",
	["JNGRCKF2"] = "concrete",
	["JNGRCKF3"] = "concrete",
	["JNGRCKF4"] = "concrete",
	["JNGWDF1"] = "wood_heavy",
	["JNGWDF1B"] = "wood_heavy",
	["JNGWDF1S"] = "wood_heavy",
	["JNGWDF2"] = "wood_heavy",
	["JNGWDF2B"] = "wood_heavy",
	["JNGWDF2S"] = "wood_heavy",
	["JNGWDF3"] = "wood_heavy",
	["JNGWDF3B"] = "wood_heavy",
	["JNGWDF3S"] = "wood_heavy",
	["JNGWDF4"] = "wood_heavy",
	["JNGWDF4B"] = "wood_heavy",
	["JNGWDF4S"] = "wood_heavy",
	["JNGWDF5"] = "wood_heavy",
	["JNGWDF6"] = "wood_heavy",
	["JNGWDF7"] = "wood_heavy",
	["JNGWDF8"] = "wood_heavy",
	["JNGWDF9"] = "wood_heavy",
	["JNGWDFA"] = "wood_heavy",
	["JNGWDFB"] = "wood_heavy",
	["JNGWDFC"] = "wood_heavy",
	["CAVEF1"] = "concrete",
	["CAVEF2"] = "concrete",
	["CAVEF3"] = "concrete",
	["CAVEF4"] = "concrete",
	["CAVEF5"] = "concrete",
	["CAVEF6"] = "concrete",
	["CAVEF7"] = "concrete",
	["CAVEF8"] = "concrete",
	["CAVEF9"] = "concrete",
	["CAVEFA"] = "concrete",
	["CAVEFB"] = "concrete",
	["XMSFLR01"] = "concrete",
	["XMSFLR02"] = "snow",
	["XMSFLR03"] = "concrete",
	["XMSFLR04"] = "concrete",
	["XMSFLR05"] = "wood_heavy",
	["XMSFLR06"] = "wood_heavy",
	["XMSFLR07"] = "concrete",
	["XMSFLR08"] = "wood_heavy",
	["XMSFLR09"] = "wood_heavy",
	["XMSFLR10"] = "wood_heavy",
	["XMSFLR11"] = "wood_heavy",
	["XMSFLR12"] = "wood_heavy",
	["XMSFLR13"] = "wood_heavy",
	["XMSFLR14"] = "wood_heavy",
	["XMSFLR15"] = "concrete",
	["XMSFLR16"] = "wood_heavy",
	["XMSFLR17"] = "concrete",
	["XMSFLR18"] = "concrete",
	["XMSFLR19"] = "concrete",
	["XMSFLR20"] = "concrete",
	["FHZICEFL"] = "concrete",
	["FGZROKFL"] = "concrete",
	["APFLOR1"] = "metal_heavy",
	["APFLOR2"] = "metal_heavy",
	["APFLOR3"] = "metal_heavy",
	["APFLOR4"] = "metal_heavy",
	["APFLOR5"] = "metal_heavy",
	["APFLOR6"] = "metal_heavy",
	["APFLOR7"] = "metal_heavy",
	["ICEFLR0"] = "concrete",
	["ICEFLR1"] = "concrete",
	["ICEFLR2"] = "concrete",
	["ICEFLR3"] = "concrete",
	["ICEFLR3S"] = "concrete",
	["ICEFLR4"] = "concrete",
	["ICEFLR4S"] = "concrete",
	["ICEFLR5"] = "concrete",
	["ICEFLR6"] = "concrete",
	["ICEFLR7"] = "concrete",
	["ICEFLR8"] = "concrete",
	["ICEFLR9"] = "glass",
	["ICEFLR9S"] = "glass",
	["ICEFLRA"] = "glass",
	["SNOW01"] = "snow",
	["SNOW02"] = "snow",
	["SNOW03"] = "snow",
	["LAKEFLR1"] = "dirt",
	["LAKEFLR2"] = "sand",
	["LAKEFLR3"] = "sand",
	["LAKEFLR4"] = "grass",
	["LAKEFLR5"] = "concrete",
	["LAKEFLR6"] = "concrete",
	["LAKEFLR7"] = "concrete",
	["LAKEFLRD"] = "concrete",
	["LAKEFLRE"] = "concrete",
	["LAKEPIF1"] = "metal_heavy",
	["LAKEPIF2"] = "metal_heavy",
	["LAKEFLRF"] = "concrete",
	["SRB1FE1"] = "concrete",
	["SRB1FIP1"] = "concrete",
	["SRB1FKB1"] = "concrete",
	["SRB1FR1"] = "metal_heavy",
	["SRB1FRB1"] = "metal_heavy",
	["SRB1FV1"] = "concrete",
	["SRB1FV2"] = "concrete",
	["SRB1FV3"] = "concrete",
	["HPFLOOR%20"] = "concrete",
	["HPEMERAL"] = "concrete",
	["MHFL1"] = "dirt",
	["MHFL2A"] = "grass",
	["MHFL2B"] = "grass",
	["MHFL3"] = "dirt",
	["MHFL4"] = "dirt",
	["LBZFLORC"] = "concrete",
	["LBZFLOR7"] = "concrete",
	["LBZFLOR8"] = "concrete",
	["LBZFLOR9"] = "concrete",
	["LBZFLORA"] = "concrete",
	["LBZFLORB"] = "concrete",
	["LBZFLR07"] = "metal_heavy",
	["LBZFLR08"] = "metal_heavy",
	["LBZFLR09"] = "metal_heavy",
	["SCBBLKF1"] = "metal_heavy",
	["SCBFLR01"] = "metal_heavy",
	["SCBFLR02"] = "metal_heavy",
	["SCBFLR03"] = "metal_heavy",
	["SCBFLR04"] = "metal_heavy",
	["NIZF01"] = "concrete",
	["HHZGRAS1"] = "grass",
	["HHZGRAS2"] = "grass",
	["HHZF1"] = "metal_heavy",
	["BSFLR1"] = "metal_heavy",
	["BSFLR1B"] = "metal_heavy",
	["BSFLR1C"] = "metal_heavy",
	["BSFLR1D"] = "metal_heavy",
	["BSFLR1DB"] = "metal_heavy",
	["BSFLR1E"] = "metal_heavy",
	["BSFLR1F"] = "metal_heavy",
	["BSFLR2"] = "metal_heavy",
	["BSFLR2B"] = "metal_heavy",
	["BSFLR2C"] = "metal_heavy",
	["BSFLR2D"] = "metal_heavy",
	["BSFLR2DB"] = "metal_heavy",
	["BSFLR2E"] = "metal_heavy",
	["BSFLR2F"] = "metal_heavy",
	["BSFLR3"] = "metal_heavy",
	["BSFLR3B"] = "metal_heavy",
	["BSFLR3C"] = "metal_heavy",
	["BSFLR3D"] = "metal_heavy",
	["BSFLR3DB"] = "metal_heavy",
	["BSFLR3E"] = "metal_heavy",
	["BSFLR3F"] = "metal_heavy",
	["BSFLR4"] = "metal_heavy",
	["BSFLR4E"] = "metal_heavy",
	["BSFLR5"] = "metal_heavy",
	["BSFLR5B"] = "metal_heavy",
	["BSFLR5C"] = "metal_heavy",
	["BSFLR5D"] = "metal_heavy",
	["BSFLR5DB"] = "metal_heavy",
	["BSFLR5E"] = "metal_heavy",
	["BSFLR5F"] = "metal_heavy",
	["BSFLR6"] = "metal_heavy",
	["BSFLR6B"] = "metal_heavy",
	["BSFLR6C"] = "metal_heavy",
	["BSFLR6D"] = "metal_heavy",
	["BSFLR6DB"] = "metal_heavy",
	["BSFLR6E"] = "metal_heavy",
	["BSFLR6F"] = "metal_heavy",
	["SCBGRATE"] = "metal_heavy",
	["HHZCRACF"] = "concrete",
	["HHZSTNF1"] = "concrete",
	["HHZSTNF2"] = "concrete",
	["WEBBIGF"] = "grass",
	["WEBBIGF2"] = "grass",
	["WEBBIGF3"] = "grass",
	["CONCBLAK"] = "concrete",
	["CONVEY1"] = "metal_heavy",
	["CONVEY2"] = "metal_heavy",
	["TOMBNTOP"] = "concrete",
	["HHZBLAC2"] = "concrete",
	["HHZBLACK"] = "concrete",
	["~000"] = "concrete",
	["~001"] = "concrete",
	["~002"] = "concrete",
	["~003"] = "concrete",
	["~004"] = "concrete",
	["~005"] = "concrete",
	["~006"] = "concrete",
	["~007"] = "concrete",
	["~008"] = "concrete",
	["~009"] = "concrete",
	["~010"] = "concrete",
	["~011"] = "concrete",
	["~012"] = "concrete",
	["~013"] = "concrete",
	["~014"] = "concrete",
	["~015"] = "concrete",
	["~016"] = "concrete",
	["~017"] = "concrete",
	["~018"] = "concrete",
	["~019"] = "concrete",
	["~020"] = "concrete",
	["~021"] = "concrete",
	["~022"] = "concrete",
	["~023"] = "concrete",
	["~024"] = "concrete",
	["~025"] = "concrete",
	["~026"] = "concrete",
	["~027"] = "concrete",
	["~028"] = "concrete",
	["~029"] = "concrete",
	["~030"] = "concrete",
	["~031"] = "concrete",
	["~032"] = "concrete",
	["~033"] = "concrete",
	["~034"] = "concrete",
	["~035"] = "concrete",
	["~036"] = "concrete",
	["~037"] = "concrete",
	["~038"] = "concrete",
	["~039"] = "concrete",
	["~040"] = "concrete",
	["~041"] = "concrete",
	["~042"] = "concrete",
	["~043"] = "concrete",
	["~044"] = "concrete",
	["~045"] = "concrete",
	["~046"] = "concrete",
	["~047"] = "concrete",
	["~048"] = "concrete",
	["~049"] = "concrete",
	["~050"] = "concrete",
	["~051"] = "concrete",
	["~052"] = "concrete",
	["~053"] = "concrete",
	["~054"] = "concrete",
	["~055"] = "concrete",
	["~056"] = "concrete",
	["~057"] = "concrete",
	["~058"] = "concrete",
	["~059"] = "concrete",
	["~060"] = "concrete",
	["~061"] = "concrete",
	["~062"] = "concrete",
	["~063"] = "concrete",
	["~064"] = "concrete",
	["~065"] = "concrete",
	["~066"] = "concrete",
	["~067"] = "concrete",
	["~068"] = "concrete",
	["~069"] = "concrete",
	["~070"] = "concrete",
	["~071"] = "concrete",
	["~072"] = "concrete",
	["~073"] = "concrete",
	["~074"] = "concrete",
	["~075"] = "concrete",
	["~076"] = "concrete",
	["~077"] = "concrete",
	["~078"] = "concrete",
	["~079"] = "concrete",
	["~080"] = "concrete",
	["~081"] = "concrete",
	["~082"] = "concrete",
	["~083"] = "concrete",
	["~084"] = "concrete",
	["~085"] = "concrete",
	["~086"] = "concrete",
	["~087"] = "concrete",
	["~088"] = "concrete",
	["~089"] = "concrete",
	["~090"] = "concrete",
	["~091"] = "concrete",
	["~092"] = "concrete",
	["~093"] = "concrete",
	["~094"] = "concrete",
	["~095"] = "concrete",
	["~096"] = "concrete",
	["~097"] = "concrete",
	["~098"] = "concrete",
	["~099"] = "concrete",
	["~100"] = "concrete",
	["~101"] = "concrete",
	["~102"] = "concrete",
	["~103"] = "concrete",
	["~104"] = "concrete",
	["~105"] = "concrete",
	["~106"] = "concrete",
	["~107"] = "concrete",
	["~108"] = "concrete",
	["~109"] = "concrete",
	["~110"] = "concrete",
	["~111"] = "concrete",
	["~112"] = "concrete",
	["~113"] = "concrete",
	["~114"] = "concrete",
	["~115"] = "concrete",
	["~116"] = "concrete",
	["~117"] = "concrete",
	["~118"] = "concrete",
	["~119"] = "concrete",
	["~120"] = "concrete",
	["~121"] = "concrete",
	["~122"] = "concrete",
	["~123"] = "concrete",
	["~124"] = "concrete",
	["~125"] = "concrete",
	["~126"] = "concrete",
	["~127"] = "concrete",
	["~128"] = "concrete",
	["~129"] = "concrete",
	["~130"] = "concrete",
	["~131"] = "concrete",
	["~132"] = "concrete",
	["~133"] = "concrete",
	["~134"] = "concrete",
	["~135"] = "concrete",
	["~136"] = "concrete",
	["~137"] = "concrete",
	["~138"] = "concrete",
	["~139"] = "concrete",
	["~140"] = "concrete",
	["~141"] = "concrete",
	["~142"] = "concrete",
	["~143"] = "concrete",
	["~144"] = "concrete",
	["~145"] = "concrete",
	["~146"] = "concrete",
	["~147"] = "concrete",
	["~148"] = "concrete",
	["~149"] = "concrete",
	["~150"] = "concrete",
	["~151"] = "concrete",
	["~152"] = "concrete",
	["~153"] = "concrete",
	["~154"] = "concrete",
	["~155"] = "concrete",
	["~156"] = "concrete",
	["~157"] = "concrete",
	["~158"] = "concrete",
	["~159"] = "concrete",
	["~160"] = "concrete",
	["~161"] = "concrete",
	["~162"] = "concrete",
	["~163"] = "concrete",
	["~164"] = "concrete",
	["~165"] = "concrete",
	["~166"] = "concrete",
	["~167"] = "concrete",
	["~168"] = "concrete",
	["~169"] = "concrete",
	["~170"] = "concrete",
	["~171"] = "concrete",
	["~172"] = "concrete",
	["~173"] = "concrete",
	["~174"] = "concrete",
	["~175"] = "concrete",
	["~176"] = "concrete",
	["~177"] = "concrete",
	["~178"] = "concrete",
	["~179"] = "concrete",
	["~180"] = "concrete",
	["~181"] = "concrete",
	["~182"] = "concrete",
	["~183"] = "concrete",
	["~184"] = "concrete",
	["~185"] = "concrete",
	["~186"] = "concrete",
	["~187"] = "concrete",
	["~188"] = "concrete",
	["~189"] = "concrete",
	["~190"] = "concrete",
	["~191"] = "concrete",
	["~192"] = "concrete",
	["~193"] = "concrete",
	["~194"] = "concrete",
	["~195"] = "concrete",
	["~196"] = "concrete",
	["~197"] = "concrete",
	["~198"] = "concrete",
	["~199"] = "concrete",
	["~200"] = "concrete",
	["~201"] = "concrete",
	["~202"] = "concrete",
	["~203"] = "concrete",
	["~204"] = "concrete",
	["~205"] = "concrete",
	["~206"] = "concrete",
	["~207"] = "concrete",
	["~208"] = "concrete",
	["~209"] = "concrete",
	["~210"] = "concrete",
	["~211"] = "concrete",
	["~212"] = "concrete",
	["~213"] = "concrete",
	["~214"] = "concrete",
	["~215"] = "concrete",
	["~216"] = "concrete",
	["~217"] = "concrete",
	["~218"] = "concrete",
	["~219"] = "concrete",
	["~220"] = "concrete",
	["~221"] = "concrete",
	["~222"] = "concrete",
	["~223"] = "concrete",
	["~224"] = "concrete",
	["~225"] = "concrete",
	["~226"] = "concrete",
	["~227"] = "concrete",
	["~228"] = "concrete",
	["~229"] = "concrete",
	["~230"] = "concrete",
	["~231"] = "concrete",
	["~232"] = "concrete",
	["~233"] = "concrete",
	["~234"] = "concrete",
	["~235"] = "concrete",
	["~236"] = "concrete",
	["~237"] = "concrete",
	["~238"] = "concrete",
	["~239"] = "concrete",
	["~240"] = "concrete",
	["~241"] = "concrete",
	["~242"] = "concrete",
	["~243"] = "concrete",
	["~244"] = "concrete",
	["~245"] = "concrete",
	["~246"] = "concrete",
	["~247"] = "concrete",
	["~248"] = "concrete",
	["~249"] = "concrete",
	["~250"] = "concrete",
	["~251"] = "concrete",
	["~252"] = "concrete",
	["~253"] = "concrete",
	["~254"] = "concrete",
	["~255"] = "concrete",
	["BSZFLOOR"] = "grass",
	["FLOWB_04"] = "grass",
	["FLOWO_04"] = "grass",
	["FLOWP_04"] = "grass",
	["FLOWR_04"] = "grass",
	["FLOWW_04"] = "grass",
	["FLOWY_04"] = "grass",
	["FWALL_04"] = "grass",
	["FWB_04"] = "grass",
	["FWBOW_04"] = "grass",
	["FWBOY_04"] = "grass",
	["FWBP_04"] = "grass",
	["FWBPW_04"] = "grass",
	["FWBPY_04"] = "grass",
	["FWBWY_04"] = "grass",
	["FWBY_04"] = "grass",
	["FWO_04"] = "grass",
	["FWOP_04"] = "grass",
	["FWOPY_04"] = "grass",
	["FWORY_04"] = "grass",
	["FWOWY_04"] = "grass",
	["FWP_04"] = "grass",
	["FWPW_04"] = "grass",
	["FWR_04"] = "grass",
	["FWW_04"] = "grass",
	["FWWY_04"] = "grass",
	["FLBWY_02"] = "grass",
	["FLOBY_02"] = "grass",
	["FLBWY_R2"] = "grass",
	["FWBWY_02"] = "grass",
	["BSZGRASF"] = "grass",
	["FLOWO_01"] = "grass",
	["FLOWR_01"] = "grass",
	["FLOWP_01"] = "grass",
	["FLOWW_01"] = "grass",
	["FLOWB_01"] = "grass",
	["FLOWY_01"] = "grass",
	["FLOWB_02"] = "grass",
	["FLOWO_02"] = "grass",
	["FLOWP_02"] = "grass",
	["FLOWR_02"] = "grass",
	["FLOWW_02"] = "grass",
	["FLOWY_02"] = "grass",
	["FLOWG_01"] = "grass",
	["FLOWP_03"] = "grass",
	["FLOWR_03"] = "grass",
	["FLOWW_03"] = "grass",
	["FLOWB_03"] = "grass",
	["FLOWO_03"] = "grass",
	["FLOWY_03"] = "grass",
	["BSZFLR01"] = "metal_heavy",
	["BSZFLR02"] = "metal_heavy",
	["BSZFLR03"] = "concrete",
	["BSZFLR04"] = "metal_heavy",
	["AGZFLR01"] = "concrete",
	["AGZFLR02"] = "concrete",
	["BLUINSID"] = "concrete",
	["BRICK1"] = "concrete",
	["BRICK2"] = "concrete",
	["BRICK3"] = "concrete",
	["BRICK4"] = "concrete",
	["BUSTFLR"] = "concrete",
	["CARPET01"] = "dirt",
	["CARPET02"] = "dirt",
	["CARPET03"] = "dirt",
	["CARPET04"] = "dirt",
	["CARPET05"] = "dirt",
	["CARPET06"] = "dirt",
	["CARPET07"] = "dirt",
	["CARPET08"] = "dirt",
	["CARPET09"] = "dirt",
	["CARPET10"] = "dirt",
	["CARPET11"] = "dirt",
	["CARPET12"] = "dirt",
	["CARPET13"] = "dirt",
	["CARPET14"] = "dirt",
	["CASINOF1"] = "concrete",
	["CASINOF2"] = "concrete",
	["CASINOF3"] = "concrete",
	["CASINOF4"] = "concrete",
	["CATFLR02"] = "metal_heavy",
	["CATFLR03"] = "metal_heavy",
	["CATFLR04"] = "metal_heavy",
	["CEIL3_1"] = "metal_heavy",
	["CEMENT2"] = "concrete",
	["CHEKSMOL"] = "concrete",
	["CHKGRASF"] = "grass",
	["D2LAVA"] = "concrete",
	["DEM1_1"] = "concrete",
	["DEM1_2"] = "grass",
	["DEM1_3"] = "metal_heavy",
	["DEM1_5"] = "sand",
	["DEM1_6"] = "wood_heavy",
	["DEZBLKF1"] = "metal_heavy",
	["DEZBLKF2"] = "metal_heavy",
	["DEZBLKF3"] = "metal_heavy",
	["DEZBLKF4"] = "metal_heavy",
	["DEZBLKF5"] = "metal_heavy",
	["DEZBLKF6"] = "metal_heavy",
	["DEZBLKF7"] = "metal_heavy",
	["DEZBLKF8"] = "metal_heavy",
	["DEZBLOKF"] = "metal_heavy",
	["DEZBRKF"] = "metal_heavy",
	["DFZCLD1"] = "concrete",
	["DFZCLD2"] = "concrete",
	["DFZCLD3"] = "concrete",
	["DIRT"] = "dirt",
	["DIRT1F"] = "dirt",
	["DIRT2F"] = "dirt",
	["DIRT3F"] = "dirt",
	["DIRT4F"] = "dirt",
	["DIRT5F"] = "dirt",
	["DISCO1"] = "concrete",
	["DISCO2"] = "concrete",
	["DISCO3"] = "concrete",
	["DISCO4"] = "concrete",
	["DISCOF1"] = "dirt",
	["DKLEAFLR"] = "grass",
	["DLAVA1"] = "concrete",
	["DLAVA2"] = "concrete",
	["DLAVA3"] = "concrete",
	["DLAVA4"] = "concrete",
	["DMAPIPE"] = "metal_heavy",
	["DMAPIPE2"] = "metal_heavy",
	["DPFLAT1"] = "concrete",
	["DPFLAT2"] = "concrete",
	["DPPILL2F"] = "concrete",
	["DPPILLRF"] = "concrete",
	["DPSAND"] = "sand",
	["DPSAND2"] = "sand",
	["EC_VINES"] = "grass",
	["EC_VINET"] = "grass",
	["ERZBLCAU"] = "metal_heavy",
	["ERZRDCAU"] = "metal_heavy",
	["ERZYLCAU"] = "metal_heavy",
	["FLAT1_2"] = "metal_heavy",
	["FLOOR0_2"] = "dirt",
	["FLOOR0_4"] = "concrete",
	["FLOOR1_2"] = "wood_heavy",
	["FLOOR1_3"] = "wood_heavy",
	["FLOOR6_1"] = "concrete",
	["FOSSIL"] = "concrete",
	["FROST01"] = "concrete",
	["FROST02"] = "concrete",
	["F_SKY1"] = "concrete",
	["GEOBMP1"] = "concrete",
	["GEOBMP1S"] = "concrete",
	["GLASS3"] = "concrete",
	["GRASS1"] = "grass",
	["GRASS2"] = "grass",
	["GRASS3"] = "grass",
	["GRASSY"] = "grass",
	["HNYLEAFF"] = "grass",
	["HONEYF"] = "concrete",
	["LFZFLR1"] = "concrete",
	["LFZFLR2"] = "grass",
	["LFZFLR3"] = "grass",
	["LFZFLR4"] = "dirt",
	["LFZFLR5"] = "dirt",
	["LIFTFLAT"] = "metal_heavy",
	["LITEB1"] = "metal_heavy",
	["LITEB2"] = "metal_heavy",
	["LITEB3"] = "metal_heavy",
	["LITEN1"] = "metal_heavy",
	["LITEN2"] = "metal_heavy",
	["LITEN3"] = "metal_heavy",
	["LITER1"] = "metal_heavy",
	["LITER2"] = "metal_heavy",
	["LITER3"] = "metal_heavy",
	["LITEY1"] = "metal_heavy",
	["LITEY2"] = "metal_heavy",
	["LITEY3"] = "metal_heavy",
	["LVASAND1"] = "concrete",
	["LVASAND2"] = "concrete",
	["MEKPIPF1"] = "metal_heavy",
	["MEKPIPF2"] = "metal_heavy",
	["MEKPIPF3"] = "metal_heavy",
	["MEKPIPF4"] = "metal_heavy",
	["MEKPIPF5"] = "metal_heavy",
	["MEKPIPF6"] = "metal_heavy",
	["MEKPIPF7"] = "metal_heavy",
	["MRNR1T1"] = "concrete",
	["MRNR1T2"] = "concrete",
	["MRNR2T1"] = "concrete",
	["MRNR2T2"] = "concrete",
	["MRNR3T1"] = "concrete",
	["MRNR3T2"] = "concrete",
	["MRNR4T1"] = "concrete",
	["MRNR4T2"] = "concrete",
	["PAZFLR01"] = "glass",
	["PAZFLR02"] = "glass",
	["PAZFLR03"] = "glass",
	["PAZFLR04"] = "glass",
	["PAZFLR05"] = "concrete",
	["PIT"] = "concrete",
	["QUIK2"] = "sand",
	["QUIK3"] = "sand",
	["QUIK4"] = "sand",
	["QUIK5"] = "sand",
	["QUIK6"] = "sand",
	["QUIK7"] = "sand",
	["QUIKNOAN"] = "sand",
	["RAINBOW1"] = "concrete",
	["RAINBOW2"] = "concrete",
	["RAINBOW3"] = "concrete",
	["RAINBOW4"] = "concrete",
	["RCZCRSF1"] = "concrete",
	["RCZCRSF2"] = "concrete",
	["RCZCRSF3"] = "concrete",
	["RCZCRSF4"] = "concrete",
	["RCZFLR1"] = "concrete",
	["RCZFLR2"] = "concrete",
	["RCZFLR3"] = "concrete",
	["RCZFLR4"] = "concrete",
	["RCZFLR5"] = "concrete",
	["RCZFLR6"] = "concrete",
	["RCZFLR7"] = "concrete",
	["RCZFLR8"] = "concrete",
	["RECORD"] = "concrete",
	["ROCKBOIL"] = "concrete",
	["ROCKBOIM"] = "concrete",
	["ROCKF1"] = "concrete",
	["ROCKF2"] = "concrete",
	["ROCKF3"] = "concrete",
	["ROCKF4"] = "concrete",
	["ROCKF5"] = "concrete",
	["ROCKFLR1"] = "concrete",
	["ROCKFLR2"] = "concrete",
	["ROCKFLR3"] = "concrete",
	["ROCKFLR4"] = "concrete",
	["ROCKMF11"] = "concrete",
	["ROCKY1F"] = "concrete",
	["ROCKY2F"] = "concrete",
	["ROCKY3F"] = "concrete",
	["ROCKY4F"] = "concrete",
	["ROCKY5F"] = "concrete",
	["ROCKY6F"] = "concrete",
	["RUINS1_1"] = "concrete",
	["RUINS1_2"] = "concrete",
	["SAND"] = "dirt",
	["SANDFLR"] = "dirt",
	["SANDFLRA"] = "concrete",
	["SANDFLRB"] = "concrete",
	["SANDFLRC"] = "concrete",
	["SEGGF01"] = "concrete",
	["SEGGF02"] = "concrete",
	["SEGGF03"] = "concrete",
	["SEGGF04"] = "concrete",
	["SEGGF05"] = "concrete",
	["SFZLEAF"] = "grass",
	["SHALEF1"] = "concrete",
	["SHALEF2"] = "concrete",
	["SHROOM1"] = "dirt",
	["SHROOM2"] = "dirt",
	["SHROOM3"] = "dirt",
	["SKY1024"] = "concrete",
	["SKY1026"] = "concrete",
	["SKY1028"] = "concrete",
	["SNDPILRA"] = "concrete",
	["SPACEYL"] = "concrete",
	["SPACEYM"] = "concrete",
	["SPACEYS"] = "concrete",
	["STONE01"] = "concrete",
	["STONEF1"] = "concrete",
	["STONEF2"] = "concrete",
	["TRAPFLR"] = "metal_heavy",
	["VENT1F"] = "metal_heavy",
	["VFZFLR01"] = "grass",
	["WOODFLR"] = "wood_heavy",
	["WOODFLR2"] = "wood_heavy",
	["WOODFLR3"] = "wood_heavy",
	["WOODFLR4"] = "wood_heavy",
	["WSPECF"] = "concrete",
	["XTRMCHK"] = "concrete",
	["YLOPIPF1"] = "concrete",
	["YLOPIPF2"] = "concrete",
	["YLOPIPF3"] = "concrete",
	["YLOPIPF4"] = "concrete",
	["ZIMFLR01"] = "concrete",
	["ZIMTILE1"] = "cloth",
	["ZIMTILE2"] = "cloth",
	["ZIMTILE3"] = "cloth",
	["ZIMTILE4"] = "cloth",
	["WOODWALL"] = "wood_heavy",
	["LEGFLR01"] = "metal_heavy",
	["LEGFLR08"] = "metal_heavy",
	["LEGFLR18"] = "metal_heavy",
	["OLDCEZF3"] = "grass",
	["D2SANDV"] = "sand",
	["DSSANDV"] = "sand",
	["SPAD01"] = "metal_heavy",
	["SPAD02"] = "metal_heavy",
	["SPAD03"] = "metal_heavy",
	["SPAD04"] = "metal_heavy",
	["SPADD01"] = "metal_heavy",
	["SPADD02"] = "metal_heavy",
	["SPADD03"] = "metal_heavy",
	["SPADD04"] = "metal_heavy",
	["BOX01"] = "wood_heavy",
	["BOX02"] = "metal_heavy",
	["BOX3"] = "metal_heavy",
	["WAVE01"] = "wood_heavy",
	["WAVE02"] = "grass",
	["WAVE03"] = "concrete",
	["WAVE04"] = "wood_heavy",
	["WAVE05"] = "wood_heavy",
	["WAVE06"] = "concrete",
	["WAVE07"] = "concrete",
	["WAVE08"] = "concrete",
	["WAVE09"] = "concrete",
	["WAVE10"] = "concrete",
	["WAVE11"] = "metal_heavy",
	["WAVE12"] = "grass",
	["WAVE13"] = "metal_heavy",
	["WAVE14"] = "concrete",
	["WAVE15"] = "grass",
	["DUSTY01"] = "sand",
	["DUSTY02"] = "concrete",
	["DUSTY03"] = "concrete",
	["DUSTY04"] = "concrete",
	["DUSTY05"] = "concrete",
	["DUSTY06"] = "concrete",
	["DUSTY07"] = "concrete",
	["DUSTY08"] = "concrete",
	["DUSTY09"] = "concrete",
	["DUSTY10"] = "concrete",
	["DUSTY11"] = "concrete",
	["DUSTY12"] = "concrete",
	["DUSTY13"] = "concrete",
	["DUSTY14"] = "concrete",
	["DUSTY15"] = "concrete",
	["DUSTY16"] = "concrete",
	["DUSTY17"] = "concrete",
	["DUSTY18"] = "concrete",
	["DUSTY19"] = "concrete",
	["DUSTY20"] = "concrete",
	["TEMP"] = "concrete",
	["TEMP2"] = "concrete",
	["WHITE01"] = "snow",
	["WHITE02"] = "snow",
	["WHITE03"] = "snow",
	["WHITE04"] = "snow",
	["WHITE05"] = "snow",
	["WHITE06"] = "concrete",
	["WHITE07"] = "glass",
	["WHITE08"] = "metal_heavy",
	["WHITE09"] = "concrete",
	["WHITE10"] = "concrete",
	["WHITE11"] = "concrete",
	["WHITE12"] = "concrete",
	["WHITE13"] = "concrete",
	["WHITE14"] = "concrete",
	["WHITE15"] = "concrete",
	["WHITE16"] = "concrete",
	["WHITE17"] = "concrete",
	["WHITE18"] = "concrete",
	["WHITE19"] = "concrete",
	["CRISIS01"] = "concrete",
	["CRISIS02"] = "concrete",
	["CRISIS03"] = "concrete",
	["CRISIS04"] = "concrete",
	["CRISIS05"] = "concrete",
	["CRISIS06"] = "water",
	["CRISIS07"] = "metal_heavy",
	["CRISIS08"] = "metal_heavy",
	["CRISIS09"] = "metal_heavy",
	["CRISIS10"] = "concrete",
	["CRISIS11"] = "concrete",
	["CRISIS12"] = "concrete",
	["CRISIS13"] = "concrete",
	["CRISIS14"] = "concrete",
	["CRISIS15"] = "concrete",
	["CRISIS16"] = "concrete",
	["CRISIS17"] = "dirt",
	["CRISIS18"] = "dirt",
	["CRISIS19"] = "metal_heavy",
	["CRISIS20"] = "metal_heavy",
	["CRISIS21"] = "concrete",
	["CRISIS22"] = "concrete",
	["FLAMEC01"] = "concrete",
	["FLAMEC02"] = "concrete",
	["FLAMEC03"] = "concrete",
	["FLAMEC04"] = "concrete",
	["FLAMEC05"] = "concrete",
	["FLAMEC06"] = "lava",
	["TRAIN01"] = "dirt",
	["TRAIN02"] = "concrete",
	["TRAIN03"] = "wood_heavy",
	["TRAIN04"] = "wood_heavy",
	["TRAIN05"] = "grass",
	["TRAIN06"] = "grass",
	["TRAIN07"] = "dirt",
	["TRAIN08"] = "concrete",
	["TRAIN09"] = "concrete",
	["TRAIN10"] = "concrete",
	["TRAIN11"] = "dirt",
	["TRAIN12"] = "dirt",
	["TRAIN13"] = "metal_heavy",
	["TRAIN14"] = "grass",
	["TRAIN15"] = "grass",
	["TRAIN16"] = "dirt",
	["TRAIN17"] = "dirt",
	["TRAIN18"] = "metal_heavy",
	["TRAIN19"] = "metal_heavy",
	["TRAIN20"] = "metal_heavy",
	["TRAIN21"] = "concrete",
	["TRAIN22"] = "concrete",
	["TRAIN23"] = "concrete",
	["TRAIN24"] = "metal_heavy",
	["TRAIN25"] = "metal_heavy",
	["TRAIN26"] = "metal_heavy",
	["TRAIN27"] = "metal_heavy",
	["TROPIC01"] = "grass",
	["TROPIC02"] = "grass",
	["TROPIC03"] = "grass",
	["TROPIC04"] = "grass",
	["TROPIC05"] = "grass",
	["TROPIC06"] = "wood_heavy",
	["TROPIC07"] = "wood_heavy",
	["TROPIC08"] = "concrete",
	["TROPIC09"] = "grass",
	["TROPIC10"] = "grass",
	["TROPIC11"] = "grass",
	["TROPIC12"] = "wood_heavy",
	["TROPIC13"] = "concrete",
	["TROPIC14"] = "concrete",
	["TROPIC15"] = "concrete",
	["TROPIC16"] = "wood_heavy",
	["TROPIC17"] = "wood_heavy",
	["TROPIC18"] = "concrete",
	["KINVAL01"] = "grass",
	["KINVAL02"] = "grass",
	["KINVAL03"] = "concrete",
	["KINVAL04"] = "grass",
	["KINVAL05"] = "concrete",
	["KINVAL06"] = "concrete",
	["KINVAL07"] = "concrete",
	["KINVAL08"] = "concrete",
	["KINVAL09"] = "concrete",
	["KINVAL10"] = "concrete",
	["KINVAL11"] = "concrete",
	["KINVAL12"] = "concrete",
	["KINVAL13"] = "concrete",
	["KINVAL14"] = "grass",
	["KINVAL15"] = "concrete",
	["KINVAL16"] = "concrete",
	["KINVAL17"] = "concrete",
	["KINVAL18"] = "concrete",
	["KINVAL19"] = "glass",
	["AQUA01"] = "metal_heavy",
	["AQUA02"] = "metal_heavy",
	["AQUA03"] = "metal_heavy",
	["AQUA04"] = "metal_heavy",
	["AQUA05"] = "metal_heavy",
	["AQUA06"] = "metal_heavy",
	["AQUA07"] = "metal_heavy",
	["AQUA08"] = "metal_heavy",
	["AQUA09"] = "metal_heavy",
	["AQUA10"] = "metal_heavy",
	["AQUA11"] = "metal_heavy",
	["AQUA12"] = "metal_heavy",
	["AQUA13"] = "metal_heavy",
	["AQUA14"] = "metal_heavy",
	["AQUA15"] = "metal_heavy",
	["AQUA16"] = "metal_heavy",
	["AQUA17"] = "metal_heavy",
	["AQUA18"] = "metal_heavy",
	["AQUA19"] = "metal_heavy",
	["AQUA20"] = "metal_heavy"
}

local footstepsfile = "client/footsteps/footsteps.dat"

local playeraniminfo = {
	["soapthehedge"] = {
		["runFrames"] = {0, 2},
		["dashFrames"] = {0, 1, 2, 3},
		["walkFrames"] = {3, 7},
		["waitFrames"] = {1},
		["milnekickFrames"] = {0, 4},
		["run"] = true,
		["dash"] = true,
		["walk"] = true,
		["idle"] = true,
		["wait"] = true,
		["milnekick"] = true,
		["superRun"] = false,
		["superDash"] = false,
		["superWalk"] = true,
		["superIdle"] = true,
		["superWait"] = false
	},
}

for skin, animinfo in pairs(playeraniminfo)
	PlayerAnimInfo[skin] = animinfo
end

local function valid(mo)
	return mo and mo.valid
end

local function reset(player)
	if player.mo and player.mo.valid
		player.lastframe = 0
		player.lastanim = nil
		player.playsound = false
		player.wasfalling = false
		player.variablesset = true
		player.groundtexture = nil
		player.lastgroundtexture = nil
		
		local file = io.openlocal(footstepsfile)
		local soundListData = SoundListInfo["sonic"]
		if file
			soundListData = SoundListInfo[file:read("*a")]
			file:close()
		end
		player.soundList = soundListData
	end
end

local function has_value (tab, val)
    for index, value in ipairs(tab) do
        if value == val then
            return true
        end
    end

    return false
end

local function getGroundTexture(mo)
    local result = nil
    
    if mo.eflags & MFE_VERTICALFLIP
		if mo.ceilingrover
			result = mo.ceilingrover.bottompic
        elseif mo.standingslope and mo.standingslope == mo.subsector.sector.c_slope
            result = mo.subsector.sector.ceilingpic
        elseif mo.ceilingz == mo.subsector.sector.ceilingheight
            result = mo.subsector.sector.ceilingpic
		end
    else
        if mo.floorrover
            result = mo.floorrover.toppic
		elseif mo.standingslope and mo.standingslope == mo.subsector.sector.f_slope
            result = mo.subsector.sector.floorpic
        elseif mo.floorz == mo.subsector.sector.floorheight
			result = mo.subsector.sector.floorpic
        end
	end
	
	return result
end

local function footstepsSoundList(player, arg)
	if player.mo and player.mo.valid
		if arg
			if SoundListInfo[arg]
				player.soundList = SoundListInfo[arg]
				CONS_Printf(player, "FootSteps Sound List setted")		
				if io
					local file = io.openlocal(footstepsfile, "w+")
					file:write(arg)
					file:close()
				end
			else
				CONS_Printf(player, "That Sound List is not available, (Main Options: sonic, s4, hl, h2, h2fun, zelda, minecraft)")
			end
		else
			CONS_Printf(player, "Set the actual FootSteps Sound List - (Main Options: sonic, s4, hl, h2, h2fun, zelda, minecraft)")
		end
	else
		CONS_Printf(player, "You can't do this right now...")
	end
end

COM_AddCommand("fssoundlist", function(player, arg)
	footstepsSoundList(player, arg)
end)

addHook("PlayerThink", function(player) 
	if player.mo and player.mo.state ~= S_PLAY_DEAD
		local panimInfo = PlayerAnimInfo[player.mo.skin]
		if panimInfo ~= nil
			if player.variablesset == nil
				reset(player)
			end
			player.groundtexture = getGroundTexture(player.mo)
			if player.groundtexture == nil and player.lastgroundtexture
				player.groundtexture = player.lastgroundtexture
			end
			local material
			local soundType
			player.playsound = false
			if P_IsObjectOnGround(player.mo)
				if not(player.wasfalling)
					if player.skidtime == 16
						player.playsound = true
						soundType = "skid"
					elseif not (player.powers[pw_carry])						
						if player.milnecarry
							if player.mo.state == S_PLAY_WALK
								player.playsound = panimInfo["run"] and (player.powers[pw_super] == 0 or panimInfo["superRun"]) and (has_value(panimInfo["runFrames"], player.mo.frame & FF_FRAMEMASK) or has_value(panimInfo["runFrames"], player.mo.frame))
							elseif player.mo.state == S_PLAY_FLY or player.mo.state == S_PLAY_SWIM
								player.playsound = panimInfo["walk"] and (player.powers[pw_super] == 0 or panimInfo["superWalk"]) and (has_value(panimInfo["walkFrames"], player.mo.frame & FF_FRAMEMASK) or has_value(panimInfo["walkFrames"], player.mo.frame))
							elseif player.mo.state == S_PLAY_GLIDE_LANDING
								player.playsound = panimInfo["idle"] and (player.powers[pw_super] == 0 or panimInfo["superIdle"]) and player.lastanim ~= player.panim
							end
						else
							if player.mo.state == S_PLAY_RUN
								player.playsound = panimInfo["run"] and (player.powers[pw_super] == 0 or panimInfo["superRun"]) and (has_value(panimInfo["runFrames"], player.mo.frame & FF_FRAMEMASK) or has_value(panimInfo["runFrames"], player.mo.frame))
							elseif player.mo.state == S_PLAY_DASH
								player.playsound = panimInfo["dash"] and (player.powers[pw_super] == 0 or panimInfo["superDash"]) and (has_value(panimInfo["dashFrames"], player.mo.frame & FF_FRAMEMASK) or has_value(panimInfo["dashFrames"], player.mo.frame))
							elseif player.mo.state == S_PLAY_WALK
								player.playsound = panimInfo["walk"] and (player.powers[pw_super] == 0 or panimInfo["superWalk"]) and (has_value(panimInfo["walkFrames"], player.mo.frame & FF_FRAMEMASK) or has_value(panimInfo["walkFrames"], player.mo.frame))
							elseif player.mo.state == S_PLAY_STND or player.mo.state == S_PLAY_EDGE
								player.playsound = panimInfo["idle"] and (player.powers[pw_super] == 0 or panimInfo["superIdle"]) and player.lastanim ~= player.panim
							elseif player.mo.state == S_PLAY_WAIT 
								player.playsound = panimInfo["wait"] and (player.powers[pw_super] == 0 or panimInfo["superWait"])  and (has_value(panimInfo["waitFrames"], player.mo.frame & FF_FRAMEMASK) or has_value(panimInfo["waitFrames"], player.mo.frame))
							elseif player.milnekick and player.mo.state == S_MILNE_KICK
								player.playsound = panimInfo["milnekick"] and (has_value(panimInfo["milnekickFrames"], player.mo.frame & FF_FRAMEMASK) or has_value(panimInfo["milnekickFrames"], player.mo.frame))
							end						
						end

						soundType = "steps"
						player.playsound = player.playsound and player.lastframe ~= player.mo.frame
						player.lastframe = player.mo.frame
						player.lastanim = player.panim
					end
				else
					player.wasfalling = false
					player.playsound = true
					soundType = "land"
				end
			else
				player.wasfalling = true
			end

			if player.playsound			
				if not (player.mo.eflags & MFE_GOOWATER)
					if player.groundtexture
						material = flatsounds[player.groundtexture]
					else
						material = "concrete"
					end
					if material ~= nil
						player.lastgroundtexture = player.groundtexture
						local sounds = player.soundList[material][soundType]
						if sounds ~= nil
							S_StartSound(player.mo, sounds[P_RandomKey(#sounds) + 1])
						end
					end
				end
				if (player.mo.eflags & MFE_TOUCHLAVA)
					local sounds = player.soundList["lava"][soundType]
					if sounds ~= nil
						S_StartSound(player.mo, sounds[P_RandomKey(#sounds) + 1])
					end
				elseif (player.mo.eflags & MFE_UNDERWATER) or (player.mo.eflags & MFE_TOUCHWATER) or (player.mo.eflags & MFE_GOOWATER)
					local sounds = player.soundList["water"][soundType]
					if sounds ~= nil
						S_StartSound(player.mo, sounds[P_RandomKey(#sounds) + 1])
					end
				end
			end
		end
	end
end)